### ISSUE TITLE
Verifying fingerprints is too unintuitive

### ISSUE THREAD

**Issue by caspear** [WhisperSystems/Signal-iOS#1099] opened 2016-03-06 11:33 UTC
I just spent about half an hour trying to tell my parents how to verify each other's fingerprint. Gave up in frustration.

Every other iOS user I know who uses signal was either unaware it was possible to verify fingerprints until I told them, or have needed to Google how to do it. Googling works fine if you speak English, but not everyone does.

It is completely not obvious that that section at the top they are supposed to long press is something that is pressable, it has terrible discoverability.

On Android there is the "Menu" button that is easy to spot and it is obviously a button in the top right corner. Could the iOS version gain something similar?

Also, as verifying fingerprints is absolutely crucial to gaining a secure session, should unverified sessions not actually prompt users to verify the fingerprints in a similar fashion Signal currently prompts users who are talking to non-Signal users?

**Comment by 2-4601** [comment] 2016-03-06 12:19
Duplicate of #637.

**Closed** 2016-03-06 18:30 UTC
