### ISSUE TITLE
Including a Self Destructing Messages 

### ISSUE THREAD

**Issue by Robertbrown92** [WhisperSystems/Signal-iOS#1029] opened 2015-12-28 01:42 UTC
adding that feature like on the OTR protocol that some clients use gonna increase the privacy of the app and will make it harder for anyone to know what messages has been written in case we have been forced to show our chat logs to anyone

**Comment by JohanDoe** [comment] 2015-12-28 09:38
Dupe of #997

**Closed** 2015-12-28 10:08 UTC
