### ISSUE TITLE
App not respecting active DoNotDisturb #2

### ISSUE THREAD

**Issue by dibblah** [WhisperSystems/Signal-iOS#983] opened 2015-12-06 18:17 UTC
"Apple doesn't give us the APIs for it." - Frederic Jacobs

How come Skype & Facebook Messenger notifications are muted by DoNotDisturb then? And all other app notifications too ...

Do you mean that Apple gives them the APIs but not you?

**Comment by FredericJacobs** [comment] 2015-12-06 19:10
I believe we're only doing this for phone calls, not messages. Right?

**Comment by dibblah** [comment] 2015-12-06 19:38
Asked a friend to send a message, like you said no notification.

But call notifications gets through DND

But notifications for calls should be possible to stop right?  since Skype calls are muted?

I actually thought that you couldn´t get a notification through even if you wanted to, was really surprised the first time it happend. I thought DND mute was handled by iOS.

**Comment by FredericJacobs** [comment] 2015-12-06 21:03
There is a trade-off to make: either we respect do not disturb for calls, but that means that we can't get continous vibration when the phone rings or we stick with the current situation.

I would lean towards sticking to what we have now because not getting continuous vibration when the phone rings is actually way worse IMO. Eventually I think we could have a setting for explaining this trade-off. But standard behaviour would still be what we have now.

**Comment by dibblah** [comment] 2015-12-07 07:05
IMO the app disturbing me when I don´t want it to ring .. ie sleeping meeting etc .. is much worse than it not vibrating continously. A setting would be very nice so I can turn off this annoying "feature"

**Comment by voltagex** [comment] 2016-01-11 00:02
Breaking the user's expectation of what Do Not Disturb means is pretty bad

**Comment by pjctech** [comment] 2016-10-24 10:18
Use CallKit for voip calls.
https://developer.apple.com/reference/callkit

It gives the Call Blocking & Identification and Do Not Disturb for free.

**Comment by TreatyOfRome** [comment] 2017-05-01 21:21
With the implementation of WebRTC calling (and CallKit integration), this issue should be fixed. I can't reproduce this issue anymore. When turning on DND, my incoming calls (and messages) are muted.

**Closed** 2017-06-14 19:36 UTC
