### ISSUE TITLE
Swiping on a conversation caused crash (and unexpected behavior)

### ISSUE THREAD

**Issue by FiloSottile** [WhisperSystems/Signal-iOS#285] opened 2015-01-06 00:06 UTC
I swiped on a conversation, saw a X for a split second, got a crash. Here's the log.
https://gist.github.com/anonymous/24dfe2af61508093ec60

Also, I expected the conversation to end in the Archive, and be recoverable :( Was it supposed to happen? Also what did happen to the key material?

**Comment by corbett** [comment] 2015-01-06 23:51
hah, no that tab has never worked for me in any iteration. I'll try with
the beta.

c

On Tue, Jan 6, 2015 at 11:48 PM, Frederic Jacobs <notifications@github.com>
wrote:

> @corbett <https://github.com/corbett>: I would only remove that button
> when @abolishme <https://github.com/abolishme> gets back at me regarding
> the design direction we're going. Emailed him to get feedback but no luck
> so far, might need to wait a few more days. @moxie0
> <https://github.com/moxie0> even mentioned that we should get rid of the
> contact list, which I'm not sure is a good idea but will follow whatever
> design decision is taken.
>
> No, if you archive discussions they should show up there. I never have had
> any issues with that, if you do have an issue with that. Either your local
> database is corrupted from the testing or there's a bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/285#issuecomment-68956037>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by corbett** [comment] 2015-01-07 00:04
I can confirm that I just tried with the beta on a fresh install that the
archive tab gives me nothing displayed after archiving a conversation.

On Tue, Jan 6, 2015 at 11:50 PM, Christine Corbett Moran <
christine.corbett@gmail.com> wrote:

> hah, no that tab has never worked for me in any iteration. I'll try with
> the beta.
>
> c
>
> On Tue, Jan 6, 2015 at 11:48 PM, Frederic Jacobs <notifications@github.com
> > wrote:
>
>> @corbett <https://github.com/corbett>: I would only remove that button
>> when @abolishme <https://github.com/abolishme> gets back at me regarding
>> the design direction we're going. Emailed him to get feedback but no luck
>> so far, might need to wait a few more days. @moxie0
>> <https://github.com/moxie0> even mentioned that we should get rid of the
>> contact list, which I'm not sure is a good idea but will follow whatever
>> design decision is taken.
>>
>> No, if you archive discussions they should show up there. I never have
>> had any issues with that, if you do have an issue with that. Either your
>> local database is corrupted from the testing or there's a bug.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/WhisperSystems/Signal-iOS/issues/285#issuecomment-68956037>
>> .
>>
>
>
>
> --
> Dr. Corbett Moran
> Rockets @ http://www.spacex.com
> Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
> Dev @ http://circleof6app.com
> Dev @ https://whispersystems.org
> www.christinecorbettmoran.com
>
>


-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment] 2015-01-07 10:16
This is surprising. Swiping to archive and not to delete?

![img_0662](https://cloud.githubusercontent.com/assets/400296/5643964/817e3842-965e-11e4-9ff5-5007f6d5eb25.PNG)
![img_0664](https://cloud.githubusercontent.com/assets/400296/5643965/81850c44-965e-11e4-8687-8450d6d64233.PNG)

**Comment by corbett** [comment] 2015-01-07 10:25
ah I'm probably just using it in an incorrect modality. my understanding
was that the default action should be archive and not delete (as in gmail)
with the idea of the inbox being a sorting ground and permanent deletion
happening either in a hidden way or within the archived section itself.

On Wed, Jan 7, 2015 at 10:16 AM, Frederic Jacobs <notifications@github.com>
wrote:

> This is surprising. Swiping to archive and not to delete?
>
> [image: img_0662]
> <https://cloud.githubusercontent.com/assets/400296/5643964/817e3842-965e-11e4-9ff5-5007f6d5eb25.PNG>
> [image: img_0664]
> <https://cloud.githubusercontent.com/assets/400296/5643965/81850c44-965e-11e4-8687-8450d6d64233.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/285#issuecomment-69002570>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment] 2015-01-07 10:29
I think we want to encourage people to have ephemeral conversations and that delete should be at least as easy to perform as archive. (We're not monetizing on data mining archived emails ;))
But that's another UX issue.

**Comment by corbett** [comment] 2015-01-07 10:30
that is true, but it makes the notion of an inbox confusing, the idea to
quickly filter through the inbox without accidentally deleting messages.
but yea UX (it confused me!)

On Wed, Jan 7, 2015 at 10:29 AM, Frederic Jacobs <notifications@github.com>
wrote:

> I think we want to encourage people to have ephemeral conversations and
> that delete should be at least as easy to perform as archive. (We're not
> monetizing on data mining archived emails ;))
> But that's another UX issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/285#issuecomment-69003958>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment] 2015-01-07 10:32
Better check in with @abolishme during WBoC about the intended behaviour there.

**Comment by corbett** [comment] 2015-01-07 10:33
yep...

On Wed, Jan 7, 2015 at 10:32 AM, Frederic Jacobs <notifications@github.com>
wrote:

> Better check in with @abolishme <https://github.com/abolishme> during
> WBoC about the intended behaviour there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/285#issuecomment-69004376>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment] 2015-02-16 09:15
Haven't seen this in a while. Code changed substantially. Closing for now.

**Closed by FredericJacobs** 2015-02-16 09:15 UTC
Labels: bug, needs reproduction
