### ISSUE TITLE
Within fingerprint view, tapping to open camera to scan is impossible to escape from without force quitting app 

### ISSUE THREAD

**Issue by grempe** [WhisperSystems/Signal-iOS#1045] opened 2016-01-16 01:41 UTC
Within the fingerprint view I can click 'tap to scan another user's fingerprint'.

If I do this, it asks me for permission to use the camera, and then starts looking for a QR code to scan.

The problem is, if I touch this accidentally, an I have no QR code to scan, it is not possible to get back to the application UI without pressing the home button, opening the app switcher view with a home button double-tab, and swiping up on Signal to force quit.

There needs to be an escape hatch in the scanning mode to allow you to return to the application.

**Comment by 2-4601** [comment] 2016-01-16 18:21
Duplicate of #957.

**Closed** 2016-01-20 00:44 UTC
