### ISSUE TITLE
Images from iPhone to Android/Desktop can not be send

### ISSUE THREAD

**Issue by Signaluser** [WhisperSystems/Signal-iOS#1227] opened 2016-06-17 13:45 UTC
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Since the last Signal-iOS Update it is impossible to send images from iOS to Android.
The iOS-App, the Android-App and the Desktop-App are up to date.

### Steps to reproduce
- Alice sends a Message from iOS: "Here look at this picutre!"
- Alice sends the Image from iOS.
- Bob receives the Message: "Here look at this picture!"
- Bob repies: "Which picture? I did not get anything! Wait. Let me have a look on my desktop app. Maybe its a fault of my Android app. No. There, I did not get anything either. Can you send it again?"
- Alice tries again. Nothing happens.
- Bob sends a image to Alice.
- Alice receives the image.

**Actual result:** 
Images from iOS to Android not sent.
**Expected result:**
Images from iOS to Android should be sent.

### Screenshots
![screen](https://cloud.githubusercontent.com/assets/19995701/16152473/5bba5850-34a2-11e6-89cd-ebf0d709feb0.jpg)

**Comment by michaelkirk** [comment] 2016-06-17 18:26
I haven't been able to reproduce this with the latest iOS release. I was able to send an image to both android and Desktop.

### Questions

- What version is Bob using on Desktop and Android?
- Have you tried this with other recipients?
- Is this an attached image from your library, or a fresh picture from your camera? Can you verify both scenarios?
- Does sending a smaller image have different behavior?
- What format is the image? jpeg, gif, etc.

**Comment by mawed** [comment] 2016-06-18 10:00
I had this issue today (on android side).

Using 
0.14.0 on Desktop
3.16.0 on android

As the other side is not so technic, I won't bother her to test other scenarious.

**Comment by michaelkirk** [comment] 2016-06-19 20:44
@mawed 
- Who sent the image?
- Is this an attached image from a library downloaded elswehere, or a fresh picture from your camera?
- What format is the image? jpeg, gif, etc.

**Comment by Signaluser** [comment] 2016-06-20 07:15
@michaelkirk 

- Android Version: 3.16.0
- Desktop Version: Signal-Desktop/0.14.0

- The attached images are: Screenshots and Photos stored on the device library
- Before the last iOS-Update, it only affected Screenshots. Now all images. (As far as we tried)
- Image filetype is jpg

Ok, we did a new series of tests:
- Images - taken from the app - were sent. At least this time.

**Comment by mawed** [comment] 2016-06-20 08:30
@michaelkirk 


   

-  Was the image sent by you (on Android) or sent by the other person (iOS)?
Sent by the other person.
-     Is this an attached image from a library downloaded elswehere, or a fresh picture from your camera?
I don't know this. I just know, it was taken on the iPhone.
-     What format is the image? jpeg, gif, et
I don't know this.

**Comment by kayovoldk** [comment] 2016-06-21 22:09
I'm seeing the same issue even when sending myself images. This error does not occur with images taken inside the app (with the take picture option) however all images stores in the device photo library are not sent and an empty message is displayed. Attempted with both .jpg and .gif files

**Comment by michaelkirk** [comment] 2016-06-21 23:53
@kayovoldk and any body else experiencing this issue, can you make sure you've provided:

- Signal Version
- iOS Version

Also a debug log might be helpful? (Settings > Advanced > Submit Debug Log) 

Choose "copy to github issue", then paste the link in this thread.

**Comment by kayovoldk** [comment] 2016-06-22 00:23
Currently on iOS 9.3.3
Signal 2.3.2

https://gist.github.com/788f1a032b697bf86e949b5cd868287d

**Comment by michaelkirk** [comment] 2016-06-22 00:32
While trying to reproduce this, I've come across some UI issues with uploading attachments. Essentially, there is no indication of a media message being sent until it's succeeded. More details here: https://github.com/WhisperSystems/Signal-iOS/issues/1231

This may account for some of the behavior. e.g. if you are on a slow/flakey network and sending a larger image, if transmission fails, you'll never know.

@kayovoldk - thanks for the info!

One more thing to try:
For the image taken in the app, which you *were* able to send, save it from Signal to your photo library (tap on the image, hit the "share" button, then save)

Then, resend that newly saved image, by choosing it from your library.

Does it succeed that time?

**Comment by michaelkirk** [comment] 2016-06-22 01:00
This might be related to https://github.com/WhisperSystems/Signal-iOS/commit/37b582beda497bf5c6139a2097efc70e539150fa which [inadvertently removed optimizing images for network transmission](https://github.com/WhisperSystems/Signal-iOS/commit/37b582beda497bf5c6139a2097efc70e539150fa#diff-cdc353260e006d747b55ce6d90702e1dL1278).

**Comment by kayovoldk** [comment] 2016-06-22 13:56
@michaelkirk did some additional testing and now seems to just be an issue with .gif files any other info that would be helpful?

**Comment by michaelkirk** [comment] 2016-06-23 19:03
@kayovoldk - the fix in #1232 is related to file size of attached images. You should see photo attachments with large filesizes *not* taken from the camera in app, regardless of format, fail more often than small ones. Photos taken in app are appropriately resized appropriately, so are less likely to fail to send. (Some amount of failure happens because networks are messy things. Retry controls are part of proposal #1231)

Otherwise, if you can share an image that fails to attach, I can look into it further.

**Comment by Signaluser** [comment] 2016-06-24 07:33
Last days, there had been a new iOS-Update.

Currently it seems to work - most times.
However, I can not provide a picture, where the sending fails for sure. 
It occurs to be some kind of random.

**Comment by Fmstrat** [comment] 2016-07-05 00:38
Just to give another report, I'm seeing this from an iOS user. They send images that were recently taken with the camera, and sometimes they come through, but not often. I have found that when they are on Wifi it seems more reliable, and they rarely come through when the iOS user is connected through LTE. This could be coincidence, but is an observation. Unfortunately they are not a tech savvy user, so getting them to send logs/etc isn't something easy to do, but I will try to reproduce with their device next time I see them. It's very difficult to track since, unlike Android, there is no way to identify if the image (or even individual messages since they are grouped) are actually delivered.

**Comment by kayovoldk** [comment] 2016-07-07 02:55
So some updates on this. Did some testing after the most recent app update. Narrowed down the issue to a specific use case which is sending a .gif file saved to iCloud Photo Library but not currently fully downloaded to the device. Verified this by saving a gif to device and immediately sent it before iCloud could "optimize" it off the device.

iOS 9.3.3
Signal 2.3.4

https://gist.github.com/6d6cf716c39bbd97dc75d0b787ef2861

**Comment by michaelkirk** [comment] 2016-07-07 14:41
Thanks for the details @kayovoldk.

How large is the .gif before sending?
What kind of network are you on - 3g/4g/wi-fi?
With the same GIF does it fail every time? Or some percentage of the time?

We released 2.3.4 yesterday evening, which properly addressed a bug introduced in 2.3 where media wasn't properly resized for sending across our network. 2.3.4 should have addressed most failures to send media.

There will still always be some level of intermittent failures on a network, especially when it's a low bandwidth cell network, but I believe the fix to that is UX related - e.g. #1231, which shows media message transmission status, and allows retry on failure, so I'm going to close this.

If people are still having  issues on the latest (2.3.4) with attachments repeatedly failing to send with a good data connection we can reopen.

**Closed by michaelkirk** 2016-07-07 14:41 UTC
Labels: bug
