### ISSUE TITLE
This item is no longer available.

### ISSUE THREAD

**Issue by iambonboncat** [WhisperSystems/Signal-iOS#2838] opened 2017-12-01 03:03 UTC
This item is no longer available.

**Comment by MichaelRupertDev** [comment] 2017-12-01 03:11
Getting this as well on my 7+ iOS 11.2

**Comment by aghorler** [comment] 2017-12-01 03:49
I can also confirm this issue on **iOS 10.3.3** (iPhone 5C) in Australia.

Signal shows in the App Store (via search), but any attempt at installation fails with "This item is no longer available".

Version of Signal in App Store: **2.19.0**

**Comment by spartan223193** [comment] 2017-12-01 05:39
Can confirm the same issue on iOS 10 11.1.2 (iPhone 8) in the United States.

Signal shows in App Store via search, but download fails with "This item is no longer available".
Version in app store: 2.19.0

Tested and confirmed on three separate devices on separate Apple accounts.

**Comment by jw4wellness** [comment] 2017-12-01 13:58
same in Canada. I just wanted to download it. Signal shows in App Store via search, but download fails with "This item is no longer available".

**Comment by svenfl** [comment] 2017-12-01 17:40
same in Germany I deleted the App to reinstall it but now I can not install the App anymore

**Comment by alexanderkyte** [comment] 2017-12-01 20:13
I was having this issue yesterday, but it works for me now

**Comment by rainerzufall** [comment] 2017-12-01 20:18
they have just confirmed that it is working again! 
> Apple has resolved the App Store issue that was preventing some iOS users from installing Signal. Thank you for your support.
https://twitter.com/whispersystems/status/936686074465869825 

@iambonboncat could you close the issue?

**Closed** 2017-12-01 20:39 UTC
