### ISSUE TITLE
iOS: Feature Request: Personalized notifications per conversation 

### ISSUE THREAD

**Issue by stormsgreatkids** [WhisperSystems/Signal-iOS#1800] opened 2017-02-22 05:40 UTC
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Feature request: Allow different notification ringtones for different conversations. 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

-Have multiple conversations 
-Receive notifications from one or more of them. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy 
Notification sounds are the same

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct 
Different notification sounds configurable for different conversations. 

### Device info

**Device**: iDevice 5se
**iOS version**: 10.2.1
**Signal version:** 2.7.1

### Link to debug log

NA

NA

**Comment by michaelkirk** [comment] 2017-03-16 16:32
dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1009

**Closed by michaelkirk** 2017-03-16 16:32 UTC
