### ISSUE TITLE
"Client Failed" error

### ISSUE THREAD

**Issue by LindyLo** [WhisperSystems/Signal-iOS#1117] opened 2016-03-17 12:11 UTC
Hi, when I try to make an audio call I see red label "Client Failed"

**Comment by LindyLo** [comment] 2016-03-17 12:15
Here is a log output 

Mar 17 13:14:42 iPhone networkd[27644] <Error>: -[NETAWDManager reportStats:metricID:] AWDServerConnection newMetricContainerWithIdentifier failed for metric 2686983, server 0x136d6a360, not reporting:
	<AWDLibnetcoreTCPConnectionReport: 0x136d39c60> {
	    cellularFallbackReport =     {
	        dataUsageSnapshotsAtNetworkEvents =         (
	                        {
	                bytesIn = 0;
	                bytesOut = 0;
	            }
	        );
	        "fallbackTimer_msecs" = 350;
	        fellback = 0;
	        networkEvents =         (
	            "NETWORK_EVENT_CELLULAR_FALLBACK_TIMER_START"
	        );
	        "timeToNetworkEvents_msecs" =         (
	            2
	        );
	    };
	    clientIdentifier = "org.whispersystems.signal";
	    connectionStatisticsReport =     {
	        DNSAnswersCached = 0;
	        "DNSResolvedTime_msecs" = 28;
	        RTTvariance = 10;
	        "appDataStallTimer_msecs" = 0;
	        appReportingDataStallCount = 0;
	        "bestRTT_msecs" = 27;
	        betterRouteEventCount = 0;
	        bytesDuplicate = 270;
	        bytesIn = 3300;
	        bytesOut = 220;
	        bytesOutOfOrder = 3000;
	        bytesRetransmitted = 0;
	        cellularFallback = 0;
	        cellularRRCConnected = 0;
	        connected = 1;
	        connectedInterfaceType = "INTERFACE_TYPE_WIFI";
	        "connectionEstablishmentTime_msecs" = 23;
	        connectionReuseCount = 0;
	        "currentRTT_msecs" = 29;
	        "flowDuration_msecs" = 30277;
	        interfaceType = "INTERFACE_TYPE_WIFI";
	        kernelReportedStalls = 1;
	        kernelReportingConnectionStalled = 0;
	        kernelReportingReadStalled = 0;
	        kernelReportingWriteStalled = 0;
	        packetsDuplicate = 0;
	        packetsIn = 5;
	        packetsOut = 1;
	        packetsOutOfOrder = 0;
	        packetsRetransmitted = 0;
	        "smoothedRTT_msecs" = 22;
	        synRetransmissionCount = 0;
	        tcpFastOpen = 0;
	        "timeToConnectionEstablishment_msecs" = 52;
	        "timeToConnectionStart_msecs" = 29;
	        "timeToDNSResolved_msecs" = 29;
	        "timeToDNSStart_msecs" = 1;
	        trafficClass = 0;
	    };
	    delegated = 0;
	    reportReason = "REPORT_REASON_FALLBACK_SIGNAL";
	}

**Comment by michaelkirk** [comment] 2016-03-17 15:06
dupe of #1115 

This is also affecting android, seems like a server side error and not specific to the iOS client.

**Comment by FredericJacobs** [comment] 2016-03-17 15:15
This was an infrastructure issue affecting Europe. Should be fixed now.

**Closed by FredericJacobs** 2016-03-17 15:15 UTC

**Comment by paoloreds** [comment] 2016-09-06 07:31
Same error appeared today sept 6th 2016

**Comment by old10** [comment] 2016-09-06 13:50
Same error for me too. (September 6th 2016)

**Comment by old10** [comment] 2016-09-07 08:50
Calling work now.
