### ISSUE TITLE
No way of entering the QR fingerprint verification menu

### ISSUE THREAD

**Issue by Ginari** [WhisperSystems/Signal-iOS#1057] opened 2016-01-25 13:37 UTC
**Expected behavior:** Hold the name in a conversation for about 2s and the verification menu appears.
**Actual behavior:** Holding the name - nothing happens. Tried several times. Killed the app, tried again. Nothing still.

Phone: iPhone 5s
Firmware: iOS 9.2.1
App Version: 2.2

**Comment by 2-4601** [comment] 2016-01-25 14:18
Duplicate of #788

**Closed** 2016-01-25 14:45 UTC
