### ISSUE TITLE
When on phone call, "Mute" and "Speaker Phone" icons do not indicate status

### ISSUE THREAD

**Issue by vdcbb** [WhisperSystems/Signal-iOS#1161] opened 2016-04-25 22:45 UTC
- [x] I have searched open and closed issues for duplicates

---
### Bug description

Describe here the issue that you are experiencing.
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
### Screenshots

This is with speaker phone ON and mute OFF. The difference is pretty subtle, especially on older screens. 

![image](https://cloud.githubusercontent.com/assets/217057/15199940/590fa93e-1797-11e6-8ed5-09b666a5b7bf.png)

Compare to something like what native phone app does, which is much clearer:
![image](https://cloud.githubusercontent.com/assets/217057/15199983/c624f196-1797-11e6-8734-c122325f6634.png)
### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by vdcbb** [comment] 2016-04-25 22:56
[Bug description]
When having a conversation over a Signal phone call, the "Mute" icon and "Speaker" icon do not indicate what state they are in (i.e., tapping them does not visually indicate whether they are enabled or disabled).

[Steps to reproduce]
1) make a phone call with Signal. 
2) During the conversation, tap the "Mute" icon (microphone with line through it).
3) Notice how the icon looks exactly the same as it did before? The icon's "status" has not changed to indicate what "state" it is in (i.e., is "Mute" enabled or disabled?).

[Expected result]
The icons should indicate visually what state they are in (i.e., are they enabled or disabled?). Tapping the icon when it is enabled should change its appearance so that it communicates it is now in a disabled state and vice versa.

[Device]
iPhone 6s
iOS version: 9.3.1
Signal version: 2.2

**Comment by big-r81** [comment] 2016-04-26 16:45
Hi  vdcbb,

I can't reproduce this. If i press these buttons, they are getting lighter (white) or darker (gray)...

**Comment by vdcbb** [comment] 2016-05-06 14:31
Okay, I can now see that there is a change from a white to a light gray. This is far from obvious. I'm assuming "white" is On and "light gray" is Off?

Perhaps this could be improved upon? The color/shade difference is hard to notice in some lighting conditions as it provides little contrast difference. And even if the sublety is noticed, I'm not sure what state is what. With iOS, I see a bright green shade for on. No color for off. Please investigate options for making the state change more obvious to the user.

**Comment by vdcbb** [comment] 2016-05-06 15:05
I explained to a friend that the icon turns from a light gray to white. My friend can barely discern a difference and has to stare at the icon and switch it back and forth to guess at its state. Both of us are forced to turn the icon on/off several times to figure out what the state is because the visual cue is totally inadequate.

**Comment by matth3w** [comment] 2016-11-05 03:59
Wouldn't this be a great opportunity to fix using CallKit that was introduced in iOS 10? It looks like it could help with audio quality as well. I know I would use Signal for phone calls much more often if it was integrated this tightly in the system. https://developer.apple.com/videos/play/wwdc2016/230/

**Comment by michaelkirk** [comment] 2017-01-09 17:36
@charlesmchen wanted to make you aware of this issue since you're working on something similar.

**Comment by michaelkirk** [comment] 2017-04-21 18:29
Fixed by https://github.com/WhisperSystems/Signal-iOS/pull/2009

Will be released in 2.11.0

**Closed by michaelkirk** 2017-04-21 18:29 UTC
Labels: needs design
