### ISSUE TITLE
Support CallKit in iOS 10

### ISSUE THREAD

**Issue by jaredStef** [WhisperSystems/Signal-iOS#1301] opened 2016-08-11 03:54 UTC
I think it would be great to support CallKit in iOS 10, so that calls taken will show as native calls over Signal rather than just notifications as demoed in this WWDC talk. https://developer.apple.com/videos/play/wwdc2016/230/

**Comment by michaelkirk** [comment] 2016-08-11 12:53
dupe of #1213

**Closed by michaelkirk** 2016-08-11 12:53 UTC
