### ISSUE TITLE
Voice calls do not work

### ISSUE THREAD

**Issue by raduzl74** [WhisperSystems/Signal-iOS#1115] opened 2016-03-17 06:36 UTC
If I try to call anyone on Signal iOS the call does not get through. Why?

**Comment by spebsd** [comment] 2016-03-17 11:50
Same issue with a "Client Error" message if I try to call. Same for my contacts. What's happening ?

**Comment by michaelkirk** [comment] 2016-03-17 15:11
This is also affecting android, seems like a server side error and not specific to the iOS client.

https://whispersystems.discoursehosting.net/t/cant-make-calls-but-sms-work-correct/218/9

**Comment by FredericJacobs** [comment] 2016-03-17 15:15
This was an infrastructure issue affecting Europe. Should be fixed now.

**Closed by FredericJacobs** 2016-03-17 15:15 UTC

**Comment by sorcer1122** [comment] 2016-04-06 11:16
I am having this issue again. Whenever I am trying to make a call, I am getting 'network error' message. Are there any issues with Signal again?

**Comment by jdrissel** [comment] 2017-10-07 16:18
I am getting something similar. When I attempt voice calls, no notification appears until the missed call shows up. Both devices are in my hand and on the same network (Sprint). Similar results with another device on ATT, only that one works maybe 1 time in 10.

**Comment by jdrissel** [comment] 2017-11-01 20:22
In my case, the cause was an ad blocking vpn app (blokada origin). The developer of this app added signal to the whitelist, which fixed it.
