### ISSUE TITLE
Auto-load earlier messages.

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1781] opened 2017-02-16 20:35 UTC
Today, if you scroll up to the top of the messages view, you see a "load earlier messages" button.

![load earlier messages](https://cloud.githubusercontent.com/assets/625803/23039903/4850c7e2-f45d-11e6-90fe-4b803b55de77.png)

Instead, I suggest we show some "there are more messages" indicator.  If the user lets scrolling come to rest while that indicator is in view, we automatically load more messages without waiting for an interaction from them.  By scrolling to the top of the view, they've already indicated their probably intent to go back further.

**Comment by michaelkirk** [comment] 2017-02-16 21:00
dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1059 can you add details to that one and close this one?

**Comment by michaelkirk** [comment] 2017-02-27 16:29
closing as dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1059

**Closed by michaelkirk** 2017-02-27 16:29 UTC
