### ISSUE TITLE
[Feature Request] Pure Black Theme

### ISSUE THREAD

**Issue by BrokenHope** [WhisperSystems/Signal-iOS#2933] opened 2018-01-16 18:21 UTC
Any chance of a pure black theme for Signal for use on the iPhone X?

Something similar to the black theme they added in Telegram would be good.

**Comment by NinebitX** [comment] 2018-01-22 19:16
Dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1019?

**Comment by michaelkirk** [comment] 2018-01-22 22:02
closing as dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1019

**Closed by michaelkirk** 2018-01-22 22:02 UTC
