### ISSUE TITLE
Message bubbles glitch when using SwiftKey keyboard

### ISSUE THREAD

**Issue by askielboe** [WhisperSystems/Signal-iOS#881] opened 2015-08-27 16:38 UTC
This issue is related to #421 and #838. But I've found a way to reliably reproduce the glitch using the SwiftKey keyboard.

This is what I'm talking about:

![Minimized bubbles.](http://i.imgur.com/BlkRZCh.png)

Steps to reproduce:
 1. Go into a chat conversation (message view).
 2. Switch from Apple keyboard to SwiftKey.
 3. Return to Inbox view.
 4. Enter into the chat conversation (message view) again.

I can recover the normal chat bubbles by going back to the Inbox and then into the Conversation again after a few seconds, as long as I _don't reveal the SwiftKey keyboard_ when I'm in the conversation view.

So my theory is that somehow the way that the SwiftKey keyboard 'slides up' when the "New Message" field is activated breaks the message bubbles on subsequent conversation views.

I also sometimes notice the chat bubbles not being drawn properly when I lock the iPhone in Signal and then unlock it some time later - even when using the Apple keyboard (see issues #421 and #838).

Hope this makes sense. Let me know if you need more information / testing.

**Comment by FredericJacobs** [comment] 2015-08-27 20:27
Exciting if true that you can reproduce it reliably! Will give it a shot

**Comment by askielboe** [comment] 2015-08-27 21:04
Hmm, seems like I can't reproduce it anymore. :( I'll keep trying and
report back.

**Comment by askielboe** [comment] 2015-08-28 07:16
The reproducability described above worked every time, but seems like Signal was in an already-bugged state when I found that

**Comment by askielboe** [comment] 2015-08-28 07:18
Whoops, wrong button. Anyway, the procedure described above worked consistently, but I guess the app had somehow already bugged. Even so it may provide some pointers to where to look.

I'll keep trying to reproduce it, but so far I've had nu luck..

**Comment by FredericJacobs** [comment] 2015-09-09 23:18
Seems like it's not related to SwiftKey. Closing since duplicate

**Closed by FredericJacobs** 2015-09-09 23:18 UTC
