### ISSUE TITLE
Dismiss keybord when message area is toucheqd

### ISSUE THREAD

**Issue by funkenstrahlen** [WhisperSystems/Signal-iOS#949] opened 2015-11-12 19:17 UTC
I would like it if the Signal app behaves like other message apps: When I start typing a message and then touch into the already received messages area (above the input row) the keybord gets dimissed. Maybe we can have that for Signal too?

**Comment by 2-4601** [comment] 2015-11-12 21:24
Duplicate of #804.

**Closed** 2015-11-12 21:28 UTC
