### ISSUE TITLE
Voice messages not rendered

### ISSUE THREAD

**Issue by bartz1** [WhisperSystems/Signal-iOS#965] opened 2015-11-22 09:58 UTC
When I send voice messaged to my friends on iOS they receive something that says "unsupported".

**Comment by mmkassem** [comment] 2015-11-23 03:20
Signal on iOS does not have voice messages.

**Comment by FredericJacobs** [comment] 2015-11-23 07:12
Duplicate of #230

**Closed by FredericJacobs** 2015-11-23 07:12 UTC

**Comment by rmueller83** [comment] 2015-11-23 08:27
I think the root cause of the message not being rendered is on the Android side: https://github.com/WhisperSystems/Signal-Android/issues/4640
