### ISSUE TITLE
HEVC and HEIF are not supported

### ISSUE THREAD

**Issue by jabs7** [WhisperSystems/Signal-iOS#2202] opened 2017-06-11 20:16 UTC
In ios11 apple introduced all videos and pictures will use HEVC and HEIF formats. Signal seems to not be able to send and receive media messages currently on the ios11 developer beta.

**Comment by charlesmchen** [comment] 2017-06-12 13:20
Thanks @jabs7 - we'll look into it.

**Comment by michaelkirk** [comment] 2017-09-06 01:49
@jabs7 

To be clear about your reproduction here:

Take a photo using the native iOS11 camera app.
Open a conversation in Signal, choose media library, and pick the image you just snapped.
This sends as a "file" rather than an image. 

Is that right?

If so, that's fixed in https://github.com/WhisperSystems/Signal-iOS/pull/2511

However you also mentioned having trouble with HEVC. I was not able to reproduce any problems sending video taken on iOS11. If you are, can you provide some more explicit steps to reproduce?

**Comment by michaelkirk** [comment] 2017-09-19 16:30
Fixed in #2511 

Please re-open if you are able to reproduce an issue with v2.16.0 or greater.

**Closed by michaelkirk** 2017-09-19 16:30 UTC
