### ISSUE TITLE
Unable to send a message to self.

### ISSUE THREAD

**Issue by nanotechz9l** [WhisperSystems/Signal-iOS#1073] opened 2016-02-09 06:16 UTC
I am unable to send myself a message.

**Comment by 2-4601** [comment] 2016-02-09 16:43
What happens when you send a message to yourself?
See #573.

**Comment by nanotechz9l** [comment] 2016-02-09 18:23
For some reason on my phone 6s I am unable to send myself a message. Signal fails to find my contact name or phone number to even begin the message phase.

**Comment by riyapenn** [comment] 2016-02-09 18:49
Not a bug.
Save yourself as a contact. That is put your number as a contact in your phone.

**Comment by nanotechz9l** [comment] 2016-02-10 17:47
Hi riyapenn, thats def the first thing I checked and issue still persists. This one is a weird one. Not too important tho.

**Comment by michaelkirk** [comment] 2016-02-28 16:12
@nanotechz9l can you clarify:

1. You have yourself as a contact, composed and sent a message to yourself, but never received it
2. You cannot add yourself as a contact, thus you cannot compose/send a message to yourself.

**Comment by michaelkirk** [comment] 2016-04-18 16:40
> You have added yourself as a contact, composed and sent a message to yourself, but never received it.
> 
> **OR**
> 
> You cannot add yourself as a contact, thus you cannot compose/send a message to yourself.

@nanotechz9l I'm closing this for now as I can't reproduce it. Please reopen if you have details.

**Closed by michaelkirk** 2016-04-18 16:40 UTC
Labels: needs reproduction

**Comment by MavrikD** [comment] 2017-03-22 03:11
Is there a feature to allow the echoed messages to show up on Desktop (encrypted)?
