### ISSUE TITLE
Encrypted Calls question stion by Darren Chaker

### ISSUE THREAD

**Issue by darrenchaker** [WhisperSystems/Signal-iOS#1355] opened 2016-09-27 16:50 UTC
Some calls over home WiFi are not clear. I use a Sophos router with 256AES, anyone have a thought how to cure this? 

Thank you, Darren Chaker

- [ ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by michaelkirk** [comment] 2016-09-27 16:55
Call quality is dupe of https://github.com/WhisperSystems/Signal-iOS/issues/50

For support try support@whispersystems.org or the forum whispersystems.discoursehosting.net

**Closed by michaelkirk** 2016-09-27 16:55 UTC
