### ISSUE TITLE
Automatically Delete Oldest Messages by setting message limiter

### ISSUE THREAD

**Issue by ND4SPEED** [WhisperSystems/Signal-iOS#1230] opened 2016-06-21 22:51 UTC
Current Situation:
IOS: cannot limit chat history on any IOS device

Solution/Suggestion:  like on Android, set message delete on IOS Device to e.g. 50 messages per chat partner.

Possible Variants: Feature suggestion: Remote Deletion of my sent messages on other chat partners devices AKA kill switch for messages, that I wrote.

Feature Suggestion
Variant A) Remote limit of my messages to automatically cut off after 50 messages in MY chat with the other chat partner
Variant B) Remote Delete my sent messages on other chat partners devices (kill my messages)

Reason: 
I want to keep control of my messages, of my lines that I sent, after I sent them.

**Comment by michaelkirk** [comment] 2016-06-22 04:41
Automatically deleting old messages on your device is dupe of https://github.com/WhisperSystems/Signal-iOS/issues/254

We won't make it possible to remotely delete messages you send to another person's devices. Ultimately, when you send your message to someone else, you're trusting them to have that message, whether or not we want to play shenanigans with making it a tiny bit more difficult for them to export those messages. Ultimately that effort could be better spent building real security features.

**Closed by michaelkirk** 2016-06-22 04:41 UTC
