### ISSUE TITLE
Feature request: password protect the application + additional erase all password

### ISSUE THREAD

**Issue by apcusro** [WhisperSystems/Signal-iOS#911] opened 2015-10-04 20:03 UTC
Would love to have the option to set a password for using the app and additionally the option to set another password, which, when entered would delete all content (all conversations). This way, when forced to enter your password you would use the special "erase all" password, and the application would just be empty or with some dummy conversation. I think a lot of people would love this option and it would be a great advantage over all other messaging applications out there.

**Comment by apcusro** [comment] 2015-10-04 20:08
Another option would be not to erase all conversations but rather to just not display the conversations.
If we go a little further, it would be great to be able to mark some conversations as "sensitive" and when you enter the special password those conversations would be just hidden.

**Comment by FredericJacobs** [comment] 2015-10-04 20:41
Duplicate of #738

**Closed by FredericJacobs** 2015-10-04 20:41 UTC
