### ISSUE TITLE
No Signal shortcut in photos sharing UI.

### ISSUE THREAD

**Issue by nanotechz9l** [WhisperSystems/Signal-iOS#1015] opened 2015-12-20 04:27 UTC
Signal needs a shortcut to be able to share a pix/live photos within the photos viewing UI.

**Comment by 2-4601** [comment] 2015-12-20 08:41
Do you mean the app extensions/sharing feature of iOS? If so then there's already an issue for that: #650.

**Comment by FredericJacobs** [comment] 2015-12-20 10:40
Duplicate of #650, thanks @2-4601

**Closed by FredericJacobs** 2015-12-20 10:40 UTC
