### ISSUE TITLE
copy&paste images don't work

### ISSUE THREAD

**Issue by JimLoose** [WhisperSystems/Signal-iOS#1023] opened 2015-12-22 22:53 UTC
when i copy an image from imessage or the photos app and paste it into a message in signal
- it either doesn't work at all
- or only pastes the image name (not the image)

**Comment by 2-4601** [comment] 2015-12-23 11:40
Dupe of #793.

**Comment by FredericJacobs** [comment] 2015-12-23 12:18
Thanks @2-4601 🍭

**Closed by FredericJacobs** 2015-12-23 12:18 UTC
