### ISSUE TITLE
Sent messages pop up in the message editing field

### ISSUE THREAD

**Issue by jhellen** [WhisperSystems/Signal-iOS#2082] opened 2017-05-09 07:36 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Previously sent messages keep popping up in the message editing field.

### Steps to reproduce
- Start writing to a contact

**Actual result:**  Previously sent message has popped up in the message editing field but it does not happen every time. So you need to erase the message editing field every time you send a message. Sometimes it has been working fine for a couple of months but then the problem reappears.
**Expected result:** The message editing field should be empty or contain previously unsent text.

### Device info

**Device**: iPhone 6
**iOS version**: 10.3.1
**Signal version:** 2.11.3

**Comment by TreatyOfRome** [comment] 2017-05-09 09:01
This is a duplicate of #1537.

**Comment by michaelkirk** [comment] 2017-05-09 14:40
closing as dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1537, fix coming in #2085

**Closed by michaelkirk** 2017-05-09 14:40 UTC

**Comment by charlesmchen** [comment] 2017-05-09 15:40
This is fixed and will ship with v2.12.
