### ISSUE TITLE
existing contacts/messages not imported w/new install on ios

### ISSUE THREAD

**Issue by TheDroneBee** [WhisperSystems/Signal-iOS#956] opened 2015-11-18 22:49 UTC
Iphone 6. All updates applied that carrier will allow. Install signal onto phone. Open signal app and see no already existing contacts/messages from days before. This is different than android experience whereas when installed signal, opened it up and found all my existing messages/contacts displayed. Is this by design?

**Comment by 2-4601** [comment] 2015-11-20 00:03
Signal iOS only sees the contacts on your phone. Previous messages from previous installs are not stored on any server – only on your devices. When you install on Android you also don't get this. What you have seen is probably your system's SMS database.
Upcoming multi-device support will change this a bit but still the messages are only stored on your devices.

Thus currently this is by design and not a bug (i.e. you can close this issue)

For further help you may contact support@whispersystems.org

**Closed** 2015-11-20 08:55 UTC
