### ISSUE TITLE
Let me see a photo fullscreen before I send it as an attachment

### ISSUE THREAD

**Issue by stephaniedietze** [WhisperSystems/Signal-iOS#1129] opened 2016-03-30 14:15 UTC
When I select a photo to send to another person, I'd like to double check and I selected the right one. Show it to me before I send and ideally, let me edit it (crop, etc.).

**Comment by riyapenn** [comment] 2016-03-30 17:30
Duplicate of " Let users review media selection before sending" https://github.com/WhisperSystems/Signal-iOS/issues/858

**Closed** 2016-03-30 18:19 UTC
