### ISSUE TITLE
2nd Call Attempt after 1 Call Completion mutes Signal

### ISSUE THREAD

**Issue by ND4SPEED** [WhisperSystems/Signal-iOS#702] opened 2015-03-10 12:15 UTC
I use IPHONE 6 Plus:
After successfully completed one call, I call the same party immediately after, but the other party does not hear me, nor I hear the other party.

Taken Steps on Iphone 6 PLUS:
I close the app on IOS, by swiping it closed.
I open the app.
I write messages to 1 or 2 of my contacts. Messages pull through.
I call one of my contacts. Contact on Android (or IOS) gets notified, secure line is esablished, call works perfectly.
I disconnect the call on IOS for the other party (either using Android Red Phone or IOS Signal).
==> I press the call button for the same contact for which I have one minute ago terminated the call. (and/or I press the call button for another contact)
==> The other person gets notified, picks up, (Line is "Active. Secured") but both of us cannot hear each other. (Radio Silence!)

This is always reproducable:
- not depending on wheter I switch apps or if I stay within Signal on IOS (tried out all variants) BEFORE making the second call
- not depending if the other Android Party is staying on Red Phone (and/or Signal for IOS testing) or switching apps (tried out all variants)
- not depending if the other Party is using Signal on IOS (so I have tested it with both android and IOS party phones)
- not depending if the screen safelock feature is on or off
- not depending if I use 4G or Wlan or 3G (other parties always used 3G)
- not depending if I call the same contact or another contact (still the second call or third or any following for any contact: the other party cant hear and I cannot hear the other party)

The only solution, to be able again to make calls (one call each time to be precise) is:
- to close the app on IOS by swiping it closed
- to re-open it after having it closed (previously by swiping)
  ==> Only then the call is working AND the other party can hear me, vice versa.

**Comment by ND4SPEED** [comment] 2015-04-01 08:06
The Bug is still there in Version 2.0.2 - just tested with an current Red Phone as partnering station.

- first call always works
- second call never (!) works

Only workable solution. Close the app and reopen it, to be able to make ONE (!) call!

**Comment by Ewarren7** [comment] 2015-04-21 14:02
Hey, I am seeing this bug with two iPhone 6s running iOS 8.3 on Signal 2.0.3 

Was very reproducible for us yesterday. The first time the app is opened the call connects and works properly. Subsequent calls would connect but neither party could hear each other. Only solution was to close the app and then it would work properly on the first call. It was not clear if both parties needed to close the app. I will try and figure that out.

**Comment by TreatyOfRome** [comment] 2017-04-11 07:16
Could be closed due to implementation of WebRTC calling?

**Comment by michaelkirk** [comment] 2017-04-11 13:36
Thanks @TreatyOfRome

Closing since we've replaced our calling system. If you continue to have the issue, please reopen, including a debug log (from both parties if possible) right after the incident occurs.

**Closed by michaelkirk** 2017-04-11 13:36 UTC
