### ISSUE TITLE
"The user is not registered" contact bug

### ISSUE THREAD

**Issue by ussjoin** [WhisperSystems/Signal-iOS#620] opened 2015-03-02 18:25 UTC
Repro steps:

1) Install Signal 2.0 from the App Store.
2) It notifies me that I'm being registered for TextSecure with the server.
3) It shows me my contacts. Most of them are on Android and appear black (indicating I can TextSecure); one is grey (indicating phone only; this was another iOS user).
4) I send a message to Alice, an Android TextSecure user. All goes well.
5) I receive a message from Bob, the grey iOS user noted in step 3.
6) I attempt to respond. I get the error: "The user is not registered."

Workaround:

7) Go to contacts, pull to refresh.
8) Bob is now black, rather than grey.
9) I go back to the conversation with Bob, and re-send the message. All is well.

My assumption is that the phone checks once on contacts-load for whether a user has TextSecure capabilities, and doesn't update that automatically. But that's a weird bug for a novice user.

**Comment by FredericJacobs** [comment] 2015-03-02 20:01
Thanks for the report, looking into it.

**Comment by vingtdeux** [comment] 2015-03-02 20:46
Alternate workaround:
Send a second message immediately. It looks like the first doesn't go through (resulting in the "The user is not registered." message), but if a second is sent right away it is delivered (no contacts scroll necessary).

**Comment by CameronBanga** [comment] 2015-03-03 05:37
Saw same behavior as @vingtdeux earlier today.

**Comment by konklone** [comment] 2015-03-03 21:55
I've been observing this on a friend's iPhone repeatedly today and yesterday. Seems to affect talking from iOS to iOS and from iOS to Android.

**Comment by thenktor** [comment] 2015-03-04 09:29
> 5) I receive a message from Bob, the grey iOS user noted in step 3.
> 6) I attempt to respond. I get the error: "The user is not registered."

Confirmed here

**Comment by joostrijneveld** [comment] 2015-03-04 15:43
Confirmed here as well. Having 'Bob' reinstall the app did not fix this, but did trigger a 'Key has changed' message. The workaround mentioned by @ussjoin worked fine.

**Comment by zmanian** [comment] 2015-03-05 02:53
The situation I documented in #640 could not be resolved with the @ussjoin work around.

**Comment by apfelkraut** [comment] 2015-03-05 08:02
My setup: iOS 8.1.3 (12B466) and Signal 2.0

> 5) I receive a message from Bob, the grey iOS user noted in step 3.
> 6) I attempt to respond. I get the error: "The user is not registered."

Can confirm step 6) and overall observed behavior. Step 5) is different for me and was in one case an Android/TextSecure user and in the other case an iOS/Signal user that both just (newly) installed the app on their device and sent me a message soon after. Side note: So I did not check the contact list of Signal before replying to them.

As workaround I first started out deleting and reinstalling the app on my device which solved the issue (this was when I first saw the issue with an Android/TextSecure user). I then discovered as alternative workaround (2nd occurrence of issue with the iOS/Signal user) that is also helps to
1.) Delete the conversation with the user
2.) Refresh the contact list of Signal
3.) Try to sent another message to this user => SUCCESS.

So my expectation as lazy user would be that the refresh of contacts is executed automatically as soon as a message is received from a user that is not yet part of my local contact list within Signal.

Hope this help! Thanks for this great apps and all of your work! Highly appreciated!

**Comment by thenktor** [comment] 2015-03-05 08:07
> So my expectation as lazy user would be that the refresh of contacts is executed automatically as soon as a message is received from a user that is not yet part of my local contact list within Signal.

That would be my simple workaround, too :)

**Closed** 2015-03-05 16:38 UTC
