### ISSUE TITLE
Landscape mode on iPad? - Support landscape mode #302

### ISSUE THREAD

**Issue by Rabendoktor** [WhisperSystems/Signal-iOS#1362] opened 2016-09-30 06:01 UTC
It would still be wonderful if Signal supported landscape mode on iPads... at least on mine (iOS 10.0.2, Signal latest version) it still does not work...

**Comment by 2-4601** [comment] 2016-09-30 10:57
Landscape support is tracked here: #937

**Comment by michaelkirk** [comment] 2016-09-30 12:41
close as dupe of #937

**Closed by michaelkirk** 2016-09-30 12:41 UTC
