### ISSUE TITLE
Last message row disappears

### ISSUE THREAD

**Issue by abdullahektor** [WhisperSystems/Signal-iOS#1368] opened 2016-10-04 09:35 UTC
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
The last row of multiline messages disappears at random (approximately happens to one in ten multiline message). Copying the entire message and pasting reveals that the last line is still there, but not visible.  

### Steps to reproduce
Send or receive enough messages with more than one line. 

### Screenshots
Screenshot from 2016-10-04
![img_8084](https://cloud.githubusercontent.com/assets/22612578/19069021/53e82f02-8a25-11e6-9db8-ae2d82d1db71.jpg)
The third message from the button is not showing the second line. 

### Device info

**Device**: iPhone 6s
**iOS version**: 10.0.2
**Signal version:** 2.52

### Link to debug log
https://gist.github.com/3617d8f64b6b2470775ab7d252c5c1df

**Comment by michaelkirk** [comment] 2016-10-04 15:56
It's the message at 10:40 that you're highlighting, right?

Do you know if there were emoji in the affected message? There is a new emoji related bug in iOS10 that sounds similar: https://github.com/jessesquires/JSQMessagesViewController/issues/1842

**Comment by michaelkirk** [comment] 2016-10-04 17:08
I know this is happening, but I haven't been able to reproduce it. I believe it's specific to the text in the message. 

Can you send me the text of a message that produces this behavior?

**Comment by abdullahektor** [comment] 2016-10-05 13:35
Thanks for the swift response @michaelkirk. Indeed, all affected messages end with an emoji. To reproduce: send a multiline message ending with :heart: or :point_up:, those are the emojis i have identified so far. The text before doesn't seem to matter.

**Comment by michaelkirk** [comment] 2016-10-05 14:03
Thanks for reporting. Got a fix for this in the next release.

**Closed** 2016-10-12 13:26 UTC

**Comment by gerfderf** [comment] 2016-11-13 09:19
This looks like it was reintroduced in 2.6.4 possibly after the fix for #1436 . iOS 10.1.1, iPhone 7, Signal 2.6.4. Sent to an iPhone 6S on iOS 10.x.x, running Signal 2.6.4.

Example text (copied from Signal desktop):
Test test test test test test test test test test test test :blush::heart::heart:

Screenshot on desktop:
![signal_desktop](https://cloud.githubusercontent.com/assets/23430725/20244644/b3978f54-a9d5-11e6-85d5-1d43d180e67a.jpg)

Screenshot from phone:
![signal_phone_screen](https://cloud.githubusercontent.com/assets/23430725/20244645/b397839c-a9d5-11e6-85f2-4aa781374827.jpg)


Looks like maybe if you write a message that just barely fits into the default input window size and end with emojis you can trigger it.

**Comment by michaelkirk** [comment] 2016-11-13 20:38
Thanks for the heads up.
