### ISSUE TITLE
List medias and save all

### ISSUE THREAD

**Issue by mgohin** [WhisperSystems/Signal-iOS#2467] opened 2017-08-24 07:01 UTC
Hi,

on Android, you can, in a conversation, list all medias and save them all, it's very useful when you change phone and want to save medias. Today you have to do it media by media and it's verrrrrryyyyyyy annoying.

**Comment by NiklasBr** [comment] 2017-08-24 07:29
Unfortunately, there is no hope for easy export or backup, see: #901, #967, #2290

Very annoying indeed!

**Comment by mgohin** [comment] 2017-08-24 07:32
Sad to read that ... I saw some posts about it but hoped it changed with time.

**Comment by michaelkirk** [comment] 2017-08-24 19:49
Export is dupe of: https://github.com/WhisperSystems/Signal-iOS/issues/967
Media gallery is dupe of: https://github.com/WhisperSystems/Signal-iOS/issues/349

**Closed by michaelkirk** 2017-08-24 19:49 UTC
