### ISSUE TITLE
Conversations not named after contact's name from iOS

### ISSUE THREAD

**Issue by NicolasCGN** [WhisperSystems/Signal-iOS#2881] opened 2017-12-13 18:06 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
The last version of Signal in the App Store tends to forget the iOS address book and conversations are named after the telephone number and signal's profile name. Signal has access to the iOS address book.

### Steps to reproduce
I wasn't able to reproduce it. The bug appears from time to time. After refreshing the contact list in Signal, conversations are properly named.

### Screenshots
![img_5198](https://user-images.githubusercontent.com/10416484/33954293-22562650-e038-11e7-9ec3-d2fcf58adf81.jpg)

### Device info

**Device**: iPhone 6s
**iOS version**: 11.2.1
**Signal version:** 2.19.2.0

### Link to debug log

https://gist.github.com/91cd48d0516bffc74ce10a75cb2118fc

**Comment by michaelkirk** [comment] 2017-12-14 17:12
Thanks for reporting. There's no smoking gun in the debug log, but hopefully #2882 solves it. 

How often do you see this? Are you a beta user? I'd be curious if you could reproduce it in the upcoming beta.

**Comment by NicolasCGN** [comment] 2017-12-14 21:10
I see it every 2-3 days.

I’m a beta user, so I wait for the next release then...

**Comment by michaelkirk** [comment] 2017-12-16 17:54
Turns out this is a bug in iOS11.2, and was not fixed by #2882.

I believe #2887 will actually fix it, coming in beta 2.19.3.2. Thanks for the report.

**Closed by michaelkirk** 2017-12-16 17:54 UTC
