### ISSUE TITLE
Feature request: Search

### ISSUE THREAD

**Issue by pjctech** [WhisperSystems/Signal-iOS#1414] opened 2016-10-24 10:07 UTC
I want to be able to search inside chats, individual chats and all chats together.

**Comment by michaelkirk** [comment] 2016-10-24 12:44
duplicate of: https://github.com/WhisperSystems/Signal-iOS/issues/646

Please search the backlog before spamming all subscribers.

**Closed by michaelkirk** 2016-10-24 12:44 UTC
