### ISSUE TITLE
OpenSSL installation failed

### ISSUE THREAD

**Issue by loki187** [WhisperSystems/Signal-iOS#1166] opened 2016-05-03 11:23 UTC
Hi,

When I want install pods, I get following error by installation of OpenSSL.
How can I install OpenSSL pod ?

> [!] /bin/bash -c 
> set -e
> VERSION="1.0.2g"
> SDKVERSION=`xcrun --sdk iphoneos --show-sdk-version 2> /dev/null`
> MIN_SDK_VERSION_FLAG="-miphoneos-version-min=7.0"
> 
> BASEPATH="${PWD}"
> CURRENTPATH="/tmp/openssl"
> ARCHS="i386 x86_64 armv7 armv7s arm64"
> DEVELOPER=`xcode-select -print-path`
> 
> mkdir -p "${CURRENTPATH}"
> mkdir -p "${CURRENTPATH}/bin"
> 
> cp "file.tgz" "${CURRENTPATH}/file.tgz"
> cd "${CURRENTPATH}"
> tar -xzf file.tgz
> cd "openssl-${VERSION}"
> 
> for ARCH in ${ARCHS}
> do
>   CONFIGURE_FOR="iphoneos-cross"
> 
>   if [ "${ARCH}" == "i386" ] || [ "${ARCH}" == "x86_64" ] ;
>   then
>     PLATFORM="iPhoneSimulator"
>     if [ "${ARCH}" == "x86_64" ] ;
>     then
>       CONFIGURE_FOR="darwin64-x86_64-cc"
>     fi
>   else
>     sed -ie "s!static volatile sig_atomic_t intr_signal;!static volatile intr_signal;!" "crypto/ui/ui_openssl.c"
>     PLATFORM="iPhoneOS"
>   fi
> 
>   export CROSS_TOP="${DEVELOPER}/Platforms/${PLATFORM}.platform/Developer"
>   export CROSS_SDK="${PLATFORM}${SDKVERSION}.sdk"
> 
>   echo "Building openssl-${VERSION} for ${PLATFORM} ${SDKVERSION} ${ARCH}"
>   echo "Please stand by..."
> 
>   export CC="${DEVELOPER}/usr/bin/gcc -arch ${ARCH} ${MIN_SDK_VERSION_FLAG}"
>   mkdir -p "${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk"
>   LOG="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/build-openssl-${VERSION}.log"
> 
>   LIPO_LIBSSL="${LIPO_LIBSSL} ${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/lib/libssl.a"
>   LIPO_LIBCRYPTO="${LIPO_LIBCRYPTO} ${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/lib/libcrypto.a"
> 
>   ./Configure ${CONFIGURE_FOR} --openssldir="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk" > "${LOG}" 2>&1
>   sed -ie "s!^CFLAG=!CFLAG=-isysroot ${CROSS_TOP}/SDKs/${CROSS_SDK} !" "Makefile"
> 
>   make >> "${LOG}" 2>&1
>   make all install_sw >> "${LOG}" 2>&1
>   make clean >> "${LOG}" 2>&1
> done
> 
> 
> echo "Build library..."
> rm -rf "${BASEPATH}/lib/"
> mkdir -p "${BASEPATH}/lib/"
> lipo -create ${LIPO_LIBSSL}    -output "${BASEPATH}/lib/libssl.a"
> lipo -create ${LIPO_LIBCRYPTO} -output "${BASEPATH}/lib/libcrypto.a"
> 
> echo "Copying headers..."
> rm -rf "${BASEPATH}/opensslIncludes/"
> mkdir -p "${BASEPATH}/opensslIncludes/"
> cp -RL "${CURRENTPATH}/openssl-${VERSION}/include/openssl" "${BASEPATH}/opensslIncludes/"
> 
> cd "${BASEPATH}"
> echo "Building done."
> 
> echo "Cleaning up..."
> rm -rf "${CURRENTPATH}"
> echo "Done."
> 
> Building openssl-1.0.2g for iPhoneSimulator 9.2 i386
> Please stand by...

**Comment by 2-4601** [comment] 2016-05-03 12:23
Please use the issue template when opening new issues. In your report there are no reproducable steps, no error messages (bash script???) and no indication what version you are using.
And this is probably a duplicate of one of [these](https://github.com/WhisperSystems/Signal-iOS/issues?utf8=%E2%9C%93&q=is%3Aissue+openssl+pod).

**Comment by loki187** [comment] 2016-05-03 12:42
There are the steps to reproduce:
1. I have clone of actual version of project direct from github
2. I run "pod install" in terminal, in project directory
3. pods are installing... But when installation of OpenSSL pod (last version 1.0.207) comes to the scene, I get log message (see above). There are not another error messages. Above is everything what I get. In this moment installation of pods ends. My collegue get the same message.
We can't install pods correctly.

**Comment by FredericJacobs** [comment] 2016-05-03 12:57
Don't worry about it, I'm well aware. I will update the OpenSSL dependency as soon as the critical update is out.

**Closed** 2016-05-04 12:34 UTC
