### ISSUE TITLE
No close icon for verifying fingerprint via camera

### ISSUE THREAD

**Issue by hidde-jan** [WhisperSystems/Signal-iOS#1155] opened 2016-04-14 11:40 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When verifying a contacts fingerprint using the camera, there is no close button visible in the lower left corner.

### Steps to reproduce
- Go to a chat window with a contact
- Tap and hold the contact name
- Tap on the camera icon

**Actual result:** There is no UI element in the lower left corner indicating you can cancel the action, but tapping in the lower left corner closes the camera and cancels the action.
**Expected result:** There should be a icon to indicate you can cancel the action.

### Screenshots

![img_2267](https://cloud.githubusercontent.com/assets/171505/14526821/55424912-0246-11e6-8c87-c805c0465730.PNG)

### Device info

**Device**: iPhone 6
**iOS version**: 9.3.1
**Signal version:** 2.2

### Link to debug log
Don't think it's necessary?

**Comment by 2-4601** [comment] 2016-04-14 12:41
Duplicate of #957.

**Comment by hidde-jan** [comment] 2016-04-14 12:42
Sorry, didn't show up in my search.

**Closed** 2016-04-14 12:44 UTC
