### ISSUE TITLE
"User not registered" error

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/Signal-iOS#625] opened 2015-03-02 20:40 UTC
I'm on textsecure, a friend of mine just updated to signal 2.0. He told me that when he tries to text me he gets an error: "user not registered".
Not sure why that is, but this is not a good start. And you're always boasting about how seamless your encryption is.......................................................

**Comment by vingtdeux** [comment] 2015-03-02 20:56
This is a duplicate of #620

**Closed** 2015-03-02 20:57 UTC
