### ISSUE TITLE
3D Touch (force press) in whitespace areas of inbox or archive crash iOS client immediately

### ISSUE THREAD

**Issue by grempe** [WhisperSystems/Signal-iOS#1044] opened 2016-01-16 01:17 UTC
I am using an iPhone 6s. I have two conversations in the inbox and my archive view is empty.

If I do a hard press (3d touch, force press) in the white areas below the list of names on either tab the application crashes immediately.

**Comment by JohanDoe** [comment] 2016-01-16 12:01
Dupe of #990 I believe. Should be fixed in next version.

**Closed** 2016-01-20 00:44 UTC
