### ISSUE TITLE
Cannot make secured calls "Client Error" message

### ISSUE THREAD

**Issue by spebsd** [WhisperSystems/Signal-iOS#1116] opened 2016-03-17 11:53 UTC
Hi guys,

It seems there is a problem on crypted calls, If I try to call someone, I get "Client Error" message in Red and the call ends.
Same for my contacts. I tried on Wifi and 3G/4G, same results.
Version 2.2 up to date.

**Comment by LindyLo** [comment] 2016-03-17 12:11
I have "Client Failed"

**Comment by spebsd** [comment] 2016-03-17 13:38
Yes it's probably "Client failed" in english, I've the app in French and it's "Erreur du client", I just translate the message in English but probably it's the same error

**Comment by michaelkirk** [comment] 2016-03-17 15:06
dupe of #1115 

This is also affecting android, seems like a server side error and not specific to the iOS client.

**Comment by FredericJacobs** [comment] 2016-03-17 15:15
This was an infrastructure issue affecting Europe. Should be fixed now.

**Closed by FredericJacobs** 2016-03-17 15:15 UTC
