### ISSUE TITLE
Contacts with no Signal app installed listed as Redphone contacts

### ISSUE THREAD

**Issue by byeskille** [WhisperSystems/Signal-iOS#1162] opened 2016-04-26 22:01 UTC
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
In the list when trying to start a new text message or call contacts with no installed Signal app are displayed with gray text and the phone - as if they have the old Redphone app with only support for calling. If one tries to call the app responds: Number not registered with Signal (Norwegian: Nummer ikke registrert hos Signal)

This is problematic when introducing new users as they get confused – for instance when seeing their grandma listed as they are sure that number is not active with Signal because it is a land line.

Might be adressed in this issue, but no description on when it will be corrected:
https://github.com/WhisperSystems/Signal-iOS/issues/1101
and what is meant by removing bloom filter? What will it replaced with? This blog post was a good description of how Signal do contact look up by bloom filter without compromising the entire contact list.. https://whispersystems.org/blog/contact-discovery/

### Steps to reproduce
- Open Signal
- Press the + in the upper right hand corner.
- Scroll through contacts
- Look for users with gray names and phone
- Press phone at number not expected to run Signal

**Actual result:** The app displays contacts that clearly is not suppose to be there. When trying to call those numbers the app gives error: Number not registered with Signal
**Expected result:** The app should only display contacts that have Signal - any other display should maybe be possibility to invite people to install app by SMS with link to app stores

### Screenshots
![signal-wrong-contact-error](https://cloud.githubusercontent.com/assets/11771452/14835575/b0ff5646-0c0a-11e6-999b-4dfa0c3b7cfc.PNG)

### Device info

**Device**: iPhone 6
**iOS version**: 9.3.1
**Signal version:** 2.2

### Link to debug log
https://gist.github.com/anonymous/c1c5bc1fdfce6b5a76e1f697d0191e54#file-org-whispersystems-signal-2016-04-26-13-52-log

**Comment by riyapenn** [comment] 2016-04-26 22:07
Duplicate of https://github.com/WhisperSystems/Signal-iOS/issues/1101

**Closed** 2016-04-27 07:13 UTC
