### ISSUE TITLE
screenshots using new iOS versions include text

### ISSUE THREAD

**Issue by h313** [WhisperSystems/Signal-iOS#2677] opened 2017-10-21 03:14 UTC
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Screenshot protection does not work in the new iOS version.

### Steps to reproduce
- be on iOS 11.0.3
- take a screenshot in a signal group chat

**Actual result:** the screenshot taken includes the text within the chat
**Expected result:** the screenshot returns no text

### Device info

**Device**: iPhone 7
**iOS version**: 11.0.3
**Signal version:** 2.17.1.1

### Link to debug log

Crash log: https://gist.github.com/c90924b0b200fc6e8637592b39fc240c

**Comment by michaelkirk** [comment] 2017-10-23 16:38
Dupe of https://github.com/WhisperSystems/Signal-iOS/issues/831#issuecomment-116306860

**Closed by michaelkirk** 2017-10-23 16:38 UTC
