### ISSUE TITLE
Feature request : Automatic Erase of the Inbox/Outbox after settime.

### ISSUE THREAD

**Issue by theochino** [WhisperSystems/Signal-iOS#906] opened 2015-09-25 17:05 UTC
Would like to see if it could be added the feature that Inbox/Outbox be erased automatically after a set time in the inbox (24 hours, etc ....) [user configurable.]

**Comment by freddymartinez9** [comment] 2015-10-05 10:27
This is already an open issue, I believe a duplicate of #254. Would one of the developers confirm?

**Comment by FredericJacobs** [comment] 2015-10-05 10:34
Correct, thanks for pointing that out.

**Closed by FredericJacobs** 2015-10-05 10:34 UTC

**Comment by theochino** [comment] 2015-10-05 13:24
Actually, it is not the same, the other one is after a set volume of message which this one is after a set of time (let say 24 hours but should be configurable.)

**Comment by FredericJacobs** [comment] 2015-10-05 15:41
Time can't be safely implemented on iOS because the app has no guarantee to get background execution time to perform deletion.

**Comment by theochino** [comment] 2015-10-05 15:54
You have a great software ... and saying that something is impossible is accepting that the computer won over the human (and I refuses; we should find our humanity with technology's help.)

The feature doesn't have to be perfect, it just need to be that I don't have to do it manually each time I use it (which is the setting I am requesting.)

If users use this app enough, you can grab the execution while in the foreground; but it will save me doing it by hand. If it wasn't too busy fighting this : http://www.nytimes.com/2015/08/12/opinion/apple-google-when-phone-encryption-blocks-justice.html I would be writing it myself.

It is the user that need to be protected, not the CPU on the the phone.
My 2 cents.

**Comment by FredericJacobs** [comment] 2015-10-05 16:02
As we will be implementing #254 we will give some thought to time-based since that's what iMessage does and probably makes more sense to the user. Your feedback has been taken into account.
