### ISSUE TITLE
Feature request: Log in

### ISSUE THREAD

**Issue by andersbjarby** [WhisperSystems/Signal-iOS#943] opened 2015-11-06 13:20 UTC
It is all great being able to send encrypted messages but It would also be great if no one could access them by getting their hands on my iOS device. So the option to log in by code or fingerprint wold be great.

**Comment by modoj** [comment] 2015-11-07 04:32
There is already option for using a pass-phrase, no? I'm only familiar with the Android app, but I assume this carries over. I use a pass-phrase and this is exactly what it does, presents a log-in when attempting to open Signal. You can even adjust the "time-out" rate if you'd rather not log-in every few minutes, or want it every time. On my phone, the option is under menu -> Privacy, it may differ on iOS.

**Comment by andersbjarby** [comment] 2015-11-09 12:02
Not in my iOS-version anyway.

**Comment by 2-4601** [comment] 2015-11-09 20:05
Duplicate of #738.

**Closed** 2015-11-09 20:30 UTC
