### ISSUE TITLE
Swiping left/right bug

### ISSUE THREAD

**Issue by EredLithui** [WhisperSystems/Signal-iOS#632] opened 2015-03-03 02:29 UTC
First of all thank you guys so much for the release!

What I found isn't a BIG issue but when swiping a conversation to the right (to un/archive) but letting go before the full swipe or sliding back to the middle and immediately afterwards swiping it to the left to delete (even when letting go of the touchscreen in between) there won't pop up the red delete icon. Instead this happens (exaggerated, though you even can see the blue un/archive icon) -> ![img_4584](https://cloud.githubusercontent.com/assets/8452742/6455376/b4d3fc20-c153-11e4-92e1-b23b942284e8.PNG)
It won't work the other way round when first swiping it to the left to delete and cancel/go back! This way swiping will just be blocked.

Another thing that I just wanted to throw in but is presumably on the list/in the making: I'd like to see a possibility to invite my contacts to Signal/Textsecure who haven't installed it yet - is that something to consider? (Problems could be to differ which OS they have but maybe a link to a Whisper Systems page with App Store/Play Store links would be possible instead?)

Anyway thanks again and all best wishes!

>I'm on an iPhone 4s, iOS 8.1.3, Signal 2.0

**Comment by corbett** [comment] 2015-03-03 02:44
a) this is intended behavior (though the blue should probably be hidden
when you come back from the right
b) this exists but may be expanded on, type a number of a friend in the
compose dialog, then an invite via sms pops up

On Mon, Mar 2, 2015 at 6:29 PM, EredLithui <notifications@github.com> wrote:

> First of all thank you guys so much for the release!
>
> What I found isn't a BIG issue but when swiping a conversation to the left
> (to un/archive) but letting go before the full swipe or sliding back to the
> middle and immediately afterwards swiping it to the right to delete (even
> when letting go of the touchscreen in between) there won't pop up the red
> delete icon. Instead this happens (exaggerated, though you even can see the
> blue un/archive icon) -> [image: img_4584]
> <https://cloud.githubusercontent.com/assets/8452742/6455376/b4d3fc20-c153-11e4-92e1-b23b942284e8.PNG>
> It won't work the other way round when first swiping it to the right to
> delete and cancel/go back! This way swiping will just be blocked.
>
> Another thing that I just wanted to throw in but is presumably on the
> list/in the making: I'd like to see a possibility to invite my contacts to
> Signal/Textsecure who haven't installed it yet - is that something to
> consider? (Problems could be to differ which OS they have but maybe a link
> to a Whisper Systems page with App Store/Play Store links would be possible
> instead?)
>
> Anyway thanks again and all best wishes!
>
> I'm on an iPhone 4s, iOS 8.1.3, Signal 2.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/632>.
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by vingtdeux** [comment] 2015-03-03 03:09
Re: b), great to know! I tried searching on a name to invite contacts, but got nothing with the name and thought we'd lost that feature for the time being. I realize this is probably low priority at the moment, but from a UX perspective, users are far less likely to search on number (because they don't know it), they'll be searching on name. 

Related (and as mentioned above), invites still send a Signal link regardless of the invited user's OS. +1 for a link to your site instead, so that users can get the platform appropriate link.

**Comment by EredLithui** [comment] 2015-03-03 13:06
a) Oh ok, my bad then! :) Thinking about it by daylight again makes sense now too!
b) Same as vingtdeux said, I'm pretty bad at memorizing numbers. An option to invite by name would be very helpful!

**Comment by JohanDoe** [comment] 2015-03-08 08:33
On b) possibility to invite. This is too hidden a feature imo. Even with this thread I couldn't get it to work in a first instance as the pop-up only comes up after you have typed 6 numbers or so. So even if you remember a telephone number you're not going to find this feature probably. 

Personally, I would rather have a clear 'invite button' somewhere.

**Comment by FredericJacobs** [comment] 2015-03-08 13:59
Closing this. b) is being discussed on #688

**Closed by FredericJacobs** 2015-03-08 13:59 UTC
