### ISSUE TITLE
Audio messages don't play on silent mode

### ISSUE THREAD

**Issue by mrphs** [WhisperSystems/Signal-iOS#1719] opened 2017-02-08 01:06 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Signal for iOS still doesn't have the capability to send audio messages, and in fact I only noticed they exist after receiving one from one of my friends who has an android. The problem? It took me 10mins to figure out how to play it.

The audio message plays muted when the phone is on silent mode. 

### Steps to reproduce
- Put the iOS phone on silent.
- Send an audio message to Signal for iOS.
- Try to play the audio message from iOS device.

**Actual result:** you tap on the play icon and nothing happens.
**Expected result:** hearing the audio message

### Device info

**Device**: iPhone 6s
**iOS version**: 10.2.1
**Signal version:** 2.6.15

**Comment by riyapenn** [comment] 2017-02-08 05:40
Closing as duplicate of https://github.com/WhisperSystems/Signal-iOS/issues/1072.  Have also renamed that issue to reflect voice notes as well.

**Closed by riyapenn** 2017-02-08 05:40 UTC

**Comment by mrphs** [comment] 2017-02-08 17:46
#1072 was closed at the time I opened this ticket. And I think the issue is better explained here. on #1072 it seems like it was simply dismissed without understanding the issue.

Anyhow here or there whatever that can get the ticket resolved is fine by me.
