### ISSUE TITLE
Ability to change font size

### ISSUE THREAD

**Issue by TheWey** [WhisperSystems/Signal-iOS#1195] opened 2016-05-24 02:18 UTC
I've been trying to move my whole family over to Signal, however one issue which keeps popping up from older members of my family is that the message font size is too small. Other messaging apps (ex. Hangouts, Messages) seem to mirror an increase in the system font size activated under Settings > General > Accessibility > Larger Text, but Signal does not.

Based on my admittedly small sample size, this seems to be an important issue for a sizable group of people. I don't think it would be terribly difficult to implement, and it would help many people to better use the app.

**Comment by 2-4601** [comment] 2016-05-24 09:48
Sounds like a duplicate of #471

**Comment by michaelkirk** [comment] 2016-05-24 15:19
As of the current beta release, there has been some work to implement dynamic type, at least in the conversation view, but more work needs to make the rest of the app dynamically sizable.

If you'd like to try it out, we'd like your feedback:
https://whispersystems.discoursehosting.net/t/call-for-ios-beta-testers-email-support-to-sign-up/349

**Comment by michaelkirk** [comment] 2016-05-24 15:20
(closed as dup of #471)

**Closed by michaelkirk** 2016-05-24 15:19 UTC
