### ISSUE TITLE
Can only call (not text) until +44 prefix added to contact's phone number.

### ISSUE THREAD

**Issue by samlanning** [WhisperSystems/Signal-iOS#1047] opened 2016-01-16 15:02 UTC
This was a friend's phone, not mine, so I have been unable to investigate fully, but this is roughly what we experienced (and it certainly feels like a blocker for UK users of signal).

It was also mentioned on the mailing list recently, and it seems others are having problems: https://lists.riseup.net/www/arc/whispersystems/2016-01/msg00070.html

1. I am listed as a contact on phone with number `07904 XXXXXX`
2. Signal installed and setup as usual.
3. 3 contacts listed, all with grayed-out name, but the "call" button seems active (did not test).
4. Edit my contact details, change number from `07904 XXXXXX` to `+44 7904 XXXXXX`
5. Go back to signal, my name becomes not grayed out, and we can text (other 2 remain grayed out).

Potentially similar to #786 and #766, but not identical so I thought it worthwhile to open another issue.

**Comment by mikeokner** [comment] 2016-02-05 19:57
I'm in the US and have a significant number of contacts on my list who are greyed out but the call button also still appears active.

After reading this issue, I tried editing the phone numbers of these contacts to begin with a "+1", however there was no change.

**Comment by riyapenn** [comment] 2016-02-05 20:22
Check the permissions: http://support.whispersystems.org/hc/en-us/articles/213133077-What-settings-or-permissions-do-I-need-to-enable-on-my-iPhone-

See support page: http://support.whispersystems.org/hc/en-us/articles/212743488-Why-are-my-contacts-different-colors-in-my-contact-list-

Contact support@whispersystems.org

**Comment by mikeokner** [comment] 2016-02-08 23:45
Thanks for the links, @riyapenn

**Comment by mikeokner** [comment] 2016-02-08 23:50
Thanks for the links @riyapenn. Unfortunately, I believe the issue is a software bug and not just a support issue. I contacted one of the people on my contacts list who is greyed out and they said they have an Android phone *without* Signal, RedPhone, or TextSecure installed, nor had they ever registered their number in the past.

After learning this, I tried tapping the phone icon to see what would happen and wound up with an error message "Number is not registered with Si..."

![img_1396](https://cloud.githubusercontent.com/assets/2965732/12903290/4c490974-ce8c-11e5-8439-82b971f4ee4c.jpg)

**Comment by wolfteeth** [comment] 2016-04-29 04:38
I am also seeing the issue described above. Some North American contacts did not have a +1 before the phone number and they appeared in gray with an active blue phone icon. Some of these contacts are not even mobile lines and are definitely not Signal users.

I have tried updating my contacts' phone numbers to include the +1, pulling down on the Signal contacts list to refresh, unregistering/reregistering with Signal, and uninstalling/reinstalling the app. My iPhone has plenty of free memory, I am on WiFi. At a loss for how to get an accurate list of Signal contacts.

**Comment by michaelkirk** [comment] 2016-05-18 17:54
@wolfteeth, @samlanning, @mikeokner Would any of you be willing to verify this behavior with the [latest Beta](https://whispersystems.discoursehosting.net/t/call-for-ios-beta-testers-email-support-to-sign-up/349/1)?

**Comment by samlanning** [comment] 2016-05-18 18:04
@michaelkirk: unfortunately i was only able to report this due to testing a friend's phone, not my own. I'll defer to others to test.

**Comment by wolfteeth** [comment] 2016-05-19 13:50
@michaelkirk I'm willing to give it a shot. I sent in a request for beta access.

**Comment by wolfteeth** [comment] 2016-05-19 19:54
@michaelkirk I have just tested the beta on my device. For me, this version appears to resolve the issue. I am no longer seeing the greyed out contacts, only contacts I know for a fact have Signal on their device.

**Comment by michaelkirk** [comment] 2016-06-17 01:25
Closing as this should have been resolved with 2.2 release. 🎉

**Closed by michaelkirk** 2016-06-17 01:25 UTC
