### ISSUE TITLE
Adding iOS user to group results in "Not supported attachment type received"

### ISSUE THREAD

**Issue by backbonemedia** [WhisperSystems/Signal-iOS#1343] opened 2016-09-23 00:00 UTC
- [x] I have searched open and closed issues for duplicates
----------------------------------------

### Bug description
Adding an iOS user to a group produces a "Not supported attachment type received" notification on the added users device. It does not matter whether the group creator is using iOS or Android.

### Steps to reproduce
- Alice (iOS or Android) creates a group with Bob (iOS) and Trudy (Android).
- Bob gets a message from Alice "Nicht unterstützter Anhangstyp erhalten." (German, something like "Not supported attachment type received"). The top bar (blue) says "Alice" instead of the group name.
- Trudy gets added to the group as usual.

**Actual result:** iOS user is not added to the group, but sees an error
**Expected result:** iOS user should be added to the group as usual

### Screenshots
![img_20160923_013723](https://cloud.githubusercontent.com/assets/17348338/18769850/09776d90-8131-11e6-8da8-04d28122561f.PNG)

### Device info
**Device**: iPhone 5
**iOS version**: 10.0.1, 8.x
**Signal version:** 2.4.2

**Comment by michaelkirk** [comment] 2016-09-23 00:47
dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1341

Until that's release, the work around is to add an avatar to your group.

**Closed by michaelkirk** 2016-09-23 00:47 UTC
