### ISSUE TITLE
GIF´s shows up as statics in iOS!

### ISSUE THREAD

**Issue by breakthecode** [WhisperSystems/Signal-iOS#964] opened 2015-11-22 07:47 UTC
Sending GIF´s from my Nexus 6 running Android 6.0 to my common law wifes iPhone 5S running latest version of iOS. All GIF´s are showing up as static images, why? No support for GIF´s on iOS or what?

**Comment by FredericJacobs** [comment] 2015-11-22 08:15
Duplicate of #525

**Closed by FredericJacobs** 2015-11-22 08:15 UTC
