### ISSUE TITLE
Add Opus Voice codec for calls

### ISSUE THREAD

**Issue by tmoehle** [WhisperSystems/Signal-iOS#699] opened 2015-03-10 09:59 UTC
Hey, 

it would be amazing if you could add the opus voice codec for calls. Both ends could negotiate their codec capabilities and if both parties support opus you'd have a much better audio quality.

Thanks!

**Comment by rmueller83** [comment] 2015-03-13 09:26
See also https://github.com/WhisperSystems/RedPhone/issues/69

**Comment by FredericJacobs** [comment] 2015-03-22 13:20
Duplicate of #50

**Closed by FredericJacobs** 2015-03-22 13:20 UTC
