### ISSUE TITLE
Change to iOS contact name/picture does not propagate to linked desktop device

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1639] opened 2017-01-25 13:57 UTC
Same as https://github.com/WhisperSystems/Signal-Android/issues/4798, but for iOS

To reproduce:

Link signal-desktop to signal-ios

Notice that a particular contact has phone number as their name
On iOS, in Contacts App, edit in correct first name and last name for that phone number (the default account for new contacts is an Exchange account). Join the signal contact entry to their existing entry which has their picture.
Send a signal message to the edited contact
What I see:
5. After (1), I see an inbox entry for every signal contact (each thread is empty).
6. In signal-desktop, new message from (4) arrives, but recipient is still listed by phone number, and no photo.

Expected behavior:
7. Inbox entry (thread) for newly edited contact would be listed in Desktop inbox using the contacts correct name and photo.

**Comment by yaneurabeya** [comment] 2017-01-29 04:25
This would be a nice enhancement.

**Comment by Aktariel** [comment] 2017-04-24 03:27
You can resolve this by forcing a contact re-sync in Signal Desktop -> Settings.

I don't know if this behavior is by design or not, but there's already a lot of furor over the way Signal handles contacts (I personally would have no issue with some kind of "push to Desktop" button or periodic sync behavior, but I suspect that many people would).

**Comment by charlesmchen** [comment] 2017-04-24 13:49
@yaneurabeya @Aktariel This is fixed in the forthcoming release v2.11.

**Comment by charlesmchen** [comment] 2017-04-24 13:50
Actually, I haven't tested whether contact avatars also auto-sync now. I'll make a note to do so.

**Closed by charlesmchen** 2017-04-24 13:49 UTC

**Comment by Aktariel** [comment] 2017-04-24 14:28
Well that's exciting. One less little friction point.

 I see that the milestone for 2.11 is complete; has the app been sent out for review? ( and more generally, is there a way for us to track the dates of upcoming releases? )
