### ISSUE TITLE
Feature Request: Share Sheet Integration

### ISSUE THREAD

**Issue by xanderdunn** [WhisperSystems/Signal-iOS#1419] opened 2016-10-26 07:09 UTC
Signal should be present in the iOS Share Sheet so that it's easy to share things in Signal from other apps.  

In this image you can see typical messaging apps like Facebook Messenger and iOS Messages listed in the iOS share sheet when I try to share a Tweet, or any other kind of content:
![share](https://cloud.githubusercontent.com/assets/1313618/19716280/c8c202d0-9b0f-11e6-9aaf-18ba6fb4f826.jpg)

Singal should appear in that list, although currently it isn't possible to add it.

**Comment by dreyhomedev** [comment] 2016-10-31 19:50
+1

**Comment by Soilman82** [comment] 2016-11-22 06:52
+1

This feature would be very nice and very helpful for user acceptance!

**Comment by iadmir** [comment] 2016-11-25 10:42
+1

**Comment by Calefornia** [comment] 2016-12-27 12:46
Not sure if #650 or this issue should be closed, but they seem to overlap in scope. An all-encompassing share extension could work for images, links, & other stuff. Currently exploring [Evernote's extension](https://github.com/evernote/ios8-share-extension-demo).

**Comment by michaelkirk** [comment] 2016-12-27 19:19
closed as dupe of #650

**Closed by michaelkirk** 2016-12-27 19:19 UTC
Labels: help wanted
