### ISSUE TITLE
ENHANCEMENT: eliminate infinite pop-ups when sound is disabled

### ISSUE THREAD

**Issue by astrostl** [WhisperSystems/Signal-iOS#719] opened 2015-03-16 00:25 UTC
If push notifications are enabled while sounds are disabled, the following pop-up appears *every single time the app is opened*.  Can this be changed to a singleton or a setting for those that don't use sound?

```
Action Required

Signal requires push notification alerts and sounds to be enabled to work properly. Please change it in the Settings app >> Notification Center >> Signal.
```

Thanks for everything you do!

**Comment by FredericJacobs** [comment] 2015-03-16 06:44
Duplicate of #630 that is part of the next release (2.0.2)

**Closed by FredericJacobs** 2015-03-16 06:44 UTC
