### ISSUE TITLE
All chat bubbles went empty

### ISSUE THREAD

**Issue by kmonkeyjam** [WhisperSystems/Signal-iOS#681] opened 2015-03-06 19:12 UTC
I got into some state where all my conversations looked like the attached screen shot.  When I killed the app, things went back to normal.

![img_0011](https://cloud.githubusercontent.com/assets/266762/6531900/94aa8d42-c3f1-11e4-9e22-4bc996adb020.PNG)

**Comment by FredericJacobs** [comment] 2015-03-06 22:14
This is a rendering bug. I don't think you have to kill the app. Reloading the view should be enough.
This is a duplicate of #421.

**Closed by FredericJacobs** 2015-03-06 22:14 UTC
