### ISSUE TITLE
[Request] Audio Messages Like Android

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-iOS#1981] opened 2017-04-14 11:58 UTC
Can you please add support for audio messages like android has.
Thanks

**Comment by TreatyOfRome** [comment] 2017-04-14 13:35
This issue is a duplicate of #230.

**Comment by michaelkirk** [comment] 2017-04-14 13:44
closing as dupe of #230. It's on the short list!

**Closed by michaelkirk** 2017-04-14 13:44 UTC
