### ISSUE TITLE
iPhone X, signal calls still not working after UPDATE

### ISSUE THREAD

**Issue by wozney** [WhisperSystems/Signal-iOS#2843] opened 2017-12-02 22:49 UTC
Signal call feature still not working after update.

Submitted request 8 days ago, updated to new signal and still not working.

Any help would be appreciated.

Check previous post for logs

**Comment by rocknjohn** [comment] 2017-12-04 12:00
Duplicate of your ticket at https://github.com/WhisperSystems/Signal-iOS/issues/2809.  Kindly close this duplicate ticket to save the devs' time so they can spend more time resolving bugs and less maintaining the issue tracker. Thanks

**Closed** 2018-01-13 01:26 UTC
