### ISSUE TITLE
Disabling the notification sound does not stop sounds while sending

### ISSUE THREAD

**Issue by ceving** [WhisperSystems/Signal-iOS#998] opened 2015-12-09 12:49 UTC
There are several issues with the notification sounds.

1. The app does not have a dedicated option to disable sounds while sending messages and disabling the notification sound also does not mute the app.
2. It is also not possible to stop repeated notification as it is possible in the [Apple messenger](http://osxdaily.com/2013/01/09/turn-off-repeat-text-message-alerts-iphone/).
3. It is quite annoying that the app generates notifications even when the phone is unlocked, the app is started and I am actually typing into the app. There is no need to notify a user, if he is starring at the screen.
4. And it is not possible to tell the app to vibrate instead of playing a sound.

**Comment by riyapenn** [comment] 2015-12-10 00:12
1. Duplicate of https://github.com/WhisperSystems/Signal-iOS/issues/867
2&3. Cannot reproduce this on a 5S on iOS 9.1 or 9.2.  Please open a separate issue (or rename this original one) and include more device and OS information.  
4. Group with 1, but toggling the silent/vibrate button on the outside of your device accomplishes this  if silent mode is allowed to vibrate (iPhone Settings > Sounds > enable 'Vibrate on Silent')

**Closed** 2015-12-10 08:00 UTC

**Comment by ceving** [comment] 2016-10-07 08:54
The issue is still unresolved. The App generates every time I send a message a sound. And there is no option to stop it. I do not want to mute the hole phone. I only want to stop the sound when I send a message.

**Comment by martinjthompson** [comment] 2016-10-07 17:37
#867 seems to be not found here: https://github.com/WhisperSystems/Signal-iOS/issues/867 (or am I missing something?)

**Comment by scottialex** [comment] 2019-07-11 12:15
Hello, has this been resolved? today is July 2019 and I'm switching from WhatsApp to Signal and I can't find a way to mute the sound when I send a message. In my iOS configuration Sounds & Haptics I have everything disabled and Signal is the only app that's making the sound...

Thank you
