### ISSUE TITLE
No time stamp in iOS version

### ISSUE THREAD

**Issue by jbourgui** [WhisperSystems/Signal-iOS#1943] opened 2017-04-07 00:46 UTC
My friends who have the android version of signal get time stamps for every message sent.  I only get a time stamp once in a while which makes parsing messages difficult.  It'd be great to see the time of every message arriving!  Thanks,

-j

- [ ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by iadmir** [comment] 2017-04-07 10:22
Dupe: https://github.com/WhisperSystems/Signal-iOS/issues/1058

**Comment by michaelkirk** [comment] 2017-04-07 16:02
closing as dupe of #1058

**Closed by michaelkirk** 2017-04-07 16:02 UTC
