### ISSUE TITLE
2.0_6.0 Outgoing Call

### ISSUE THREAD

**Issue by uxyoko** [WhisperSystems/Signal-iOS#368] opened 2015-01-16 20:16 UTC
![2 0_7 0_outgoing_call](https://cloud.githubusercontent.com/assets/3347534/5783816/921f0bee-9d94-11e4-992f-8b7df764c246.jpg)

**Comment by corbett** [comment] 2015-01-16 22:08
I don't think we need a keypad button here! this is for input which we won't be taking @uxyoko @abolishme

**Comment by corbett** [comment] 2015-01-20 07:04
- [ ] speaker button assets
- [ ] test on iPhone 5/6/6+

**Comment by abolishme** [comment] 2015-01-22 00:19
duplicate of #370

**Closed** 2015-01-22 00:19 UTC
Labels: design
