### ISSUE TITLE
(Unbreakable?) (Japanese?) text only displayed in part

### ISSUE THREAD

**Issue by pipping** [WhisperSystems/Signal-iOS#1450] opened 2016-11-11 13:01 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I've received a snippet of text in Japanese. What the signal app showed me was clearly incomplete, though. My impression is that signal, being unable to break the line (because it does not contain any space characters yet is too long to fit on a single line) chose to drop anything that exceeded the first line. The text was properly delivered: If I copy and paste from the message and view it in another app or if I view the message from within the Chrome Signal app, I get the correct text.

### Steps to reproduce
I have not tried to reproduce this but would assume that sending a sufficiently long snippet of Japanese characters (maybe it can be any kind of letters) without spaces(!) suffices.

### Screenshots
Again, the text that I expect: 私のハウスメートは酔っぱらくてうるさい帰りました.

What I get with the **Chrome desktop app**:
<img width="20%" alt="signal-chrome" src="https://cloud.githubusercontent.com/assets/61962/20215687/536d0d22-a816-11e6-9d9b-f7cb76db9329.png">

What I get in the **iOS app**:
<img width="20%" alt="signal-ios" src="https://cloud.githubusercontent.com/assets/61962/20215680/46ac46a2-a816-11e6-9d19-1d598c7d2bdf.png">

### Device info

**Device**: iPhone 6s
**iOS version**: 10.2
**Signal version:** 2.6.3

**Comment by michaelkirk** [comment] 2016-11-11 13:04
Sounds like a dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1422.

If you want to see if the latest beta fixes it, email me at michael@whispersystems.org.

**Closed by michaelkirk** 2016-11-11 13:04 UTC

**Comment by pipping** [comment] 2016-11-11 13:26
I'm no longer seeing this issue with version 2.6.4 (14).
