### ISSUE TITLE
Registering new keys over iOS breaks other devices without prior notice

### ISSUE THREAD

**Issue by dharma-guardian** [WhisperSystems/Signal-iOS#1041] opened 2016-01-12 11:36 UTC
So, I did something stupid, but the outcome still should have been prevented.

I wanted to have a look at the iOS version, but don't have an iPhone around. I downloaded the iPhone version on my iPad 2 and was asked to enter a phone number to receive my code. I do not have a SIM card in the iPad, just use Wifi. I received the text on my Android phone and used it on the tablet. The registering process worked out and the app tells me I'm connect, but **my other devices do not work anymore**.
A friend told she got the message, I have new keys, so I guess the other device have the old ones and therefore can not be used anymore.
If so, shouldn't Signal tell me this might happen?

**Update:** After removing registration on Android and registering again Android works again: WhisperSystems/Signal-Android#5057 Still an undesirable outcome.

iPhone Version: iPad2,2, iOS Version: 9.2
Degub log: https://gist.github.com/anonymous/5f5687c9a3e310ba241d

No "connection" on Sony D5503 (Z1 compact) with Android 5.1.1 and Signal 3.9.1
Debug Log: https://gist.github.com/anonymous/732a869389a8358d1588
![screenshot_signal_android](https://cloud.githubusercontent.com/assets/1899308/12261978/ecf43394-b924-11e5-82f0-5b6574055967.png)

No connection and install view again on Mac OS 10.10.5 with Chrome 47.0.2526.106 and the current master branch of Signal-Desktop
https://gist.github.com/0e72a217c93d45c8cb8d
<img width="635" alt="screenshot_signal_dekstop_messagedetails" src="https://cloud.githubusercontent.com/assets/1899308/12262454/5e0a2e32-b928-11e5-953d-9b5f1ce39259.png">
<img width="809" alt="screenshot_signaldesktop_register" src="https://cloud.githubusercontent.com/assets/1899308/12262456/60a3f696-b928-11e5-975b-18dbb1317cbb.png">

**Comment by 2-4601** [comment] 2016-01-12 13:49
Seems like a dupe of #959.

**Comment by dharma-guardian** [comment] 2016-01-12 13:57
Yes, it is. Did search the issues, but without finding that one.

**Closed** 2016-01-12 20:05 UTC
