### ISSUE TITLE
Read but cannot send messages in a group

### ISSUE THREAD

**Issue by zmanian** [WhisperSystems/Signal-iOS#1460] opened 2016-11-14 02:50 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### 
I am in a group chat. This group chat existed between a device re-registration.

On the Desktop client, I can send and receive messages in the group as usual.

On the iOS client, I can only recieve messages in the group. The Text entry box to send messages does not appear.

Here is a debug log from the device.
https://gist.github.com/anonymous/604120d0ddf78d0d7e3f87a85d8f54df#file-org-whispersystems-signal-2016-11-11-13-03-log

I wouldn't know how to reproduce but something like the following sequence preceded this.

1. Create a Signal Group on iOS.
2. Link Device to Desktop
3. Reregister iOS device.

**Comment by zmanian** [comment] 2016-11-14 03:04
If I had a theory, I think something is happening where messages are being synced back from the desktop client to mobile client but the mobile client didn't properly register into the group.

**Comment by michaelkirk** [comment] 2016-11-14 18:46
dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1337

Can you have someone "update" the group? That will re-broadcast the group state and you're client will realize who is in the group (including you).

**Closed by michaelkirk** 2016-11-14 18:46 UTC

**Comment by zmanian** [comment] 2016-11-14 18:51
Yep that worked! So confirmed #1337
