### ISSUE TITLE
Sending photos result in empty bubble

### ISSUE THREAD

**Issue by sschritt** [WhisperSystems/Signal-iOS#293] opened 2015-01-06 17:20 UTC
When sending a photo it first shows "Uploading attachment", then the photo is displayed for a split second, then an empty bubble remains. Logs contain "We retreived an attachment that doesn't have a known type : (null)"

![bubble](https://cloud.githubusercontent.com/assets/10422786/5632601/4bf08e8e-95d0-11e4-8f5b-8bd2e313d144.png)

**Comment by corbett** [comment] 2015-01-06 23:56
OK.. I will assign to me then. but if you happen to get a clue make sure to
update this issue with what you think it might be. I haven't seen this
myself. maybe something to do with sending a non png?

On Tue, Jan 6, 2015 at 11:26 PM, Frederic Jacobs <notifications@github.com>
wrote:

> Need to investigate. No clue yet why this happens intermittently. I
> haven't been able to reproduce it myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/293#issuecomment-68953672>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment] 2015-01-06 23:58
Well, the thing that strikes me from the bug report is that @sschritt says he sends an attachment but that he can read in the log that he receives an attachment. I'm not sure what's going on. Probably worth checking how that could happen.

**Comment by sschritt** [comment] 2015-01-07 06:46
The described behavior occurred while sending an attachment to myself. Would have been an important detail in the bug report, sry...

**Comment by corbett** [comment] 2015-01-07 08:25
Yes! We have a declare issue involving behavior for sending messages to the same number signal is registered to on that same device. For now it is undefined

**Comment by corbett** [comment] 2015-01-07 09:33
this is now deemed a duplicate of #274 which will fix the issue.

**Closed by corbett** 2015-01-07 09:33 UTC
Labels: bug
