### ISSUE TITLE
Repeated Force Close (FC) on startup.

### ISSUE THREAD

**Issue by highdiver2000** [WhisperSystems/Signal-iOS#1200] opened 2016-05-26 09:15 UTC
Android 6.01 (Sultanxda build of CM13 on OnePlus One).

Cannot launch Signal App, keeps FC.  Attached is the catlog.

Just before this, 2 things happened.  I received an SMS, not read.  A call came and I rejected with SMS.

Now I can't launch the app at all.
[logcat_and_device_info.zip](https://github.com/WhisperSystems/Signal-iOS/files/283805/logcat_and_device_info.zip)

**Comment by 2-4601** [comment] 2016-05-26 12:54
Looks like you accidentally opened this on the wrong repository :smiley: 
This is [solved](https://github.com/WhisperSystems/Signal-Android/commit/49a539a9851441036ba12ec095f1cb7d059c2eaa) in 3.16.0. And possibly on some newer CM versions too (https://github.com/WhisperSystems/Signal-Android/issues/5454#issuecomment-219032453).

Duplicate of https://github.com/WhisperSystems/Signal-Android/issues/5454

**Closed** 2016-05-26 16:06 UTC
