### ISSUE TITLE
Error joining Android Groups "Received unsupported attachment type"

### ISSUE THREAD

**Issue by ndhill84** [WhisperSystems/Signal-iOS#1344] opened 2016-09-23 03:05 UTC
- [ X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug descriptio
When getting a group invitation from an Android user the invitation shows up as "Received Unsupported attachment type"

### Steps to reproduce
- Being sent a group invite from an Android user

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The invitation comes in as Unsupported attachment type. 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
I would be able to join the group. 

### Device info

**Device**: iphone6+
**iOS version**: 9.3.4 (13G35)
**Signal version:** 2.4.2

**Comment by ndhill84** [comment] 2016-09-23 03:06
Log URL: https://gist.github.com/5fe711cfef88145e428d1da9fcb1dca2

**Comment by 2-4601** [comment] 2016-09-23 09:39
Could you ask your Android friend if the group has an avatar image? And if it has, what type of an image is it?

**Comment by michaelkirk** [comment] 2016-09-23 11:44
dupe of #1341 

> This was a new bug introduced in 2.4.2. It only affects groups without avatars though. The work-around is to add a group avatar.
> 
> It'll be fixed properly in the forthcoming 2.5 release with WhisperSystems/SignalServiceKit@1824af5

**Closed** 2016-09-23 11:44 UTC
