### ISSUE TITLE
Disappearing messages don’t vanish

### ISSUE THREAD

**Issue by maltemayer** [WhisperSystems/Signal-iOS#1428] opened 2016-10-31 13:54 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Messages marked for auto-deletion don’t disappear. Unless the App is restarted.

### Steps to reproduce
- set TLL for disappearing messages
- send messages
- wait for the TTL to expire

**Actual result:** The hourglass flashes and eventually stops. Nothing further happens.
**Expected result:** The message should disappear.

### Device info

**Device**: iPhone 5
**iOS version**: 10.1
**Signal version:** 2.6.3.10 beta

### Link to debug log

https://gist.github.com/e1fe55cc0e6c3a2d334a064d9605b9bf

**Comment by michaelkirk** [comment] 2016-10-31 13:55
Thanks for reporting.

There’s a lot in that log. Can you give me a hint as to when you sent the message and what the duration was?

**Comment by maltemayer** [comment] 2016-10-31 14:53
I’m not sure. Here is a new log. I sent a message today at 09:49 with a duration of 6h.
https://gist.github.com/18dcd4473cd64aaf251b74a5cac008ea

**Comment by michaelkirk** [comment] 2016-10-31 14:58
So, you sent a 6h disappearing message at 9:49,and it looks like you launched the app again 6 hours later at 15:50. 

Sorry to be obtuse but… was it deleted when you opened the app? Or what did you see?

What I’m trying to do is find logging corresponding to the incorrect behavior.

**Comment by maltemayer** [comment] 2016-10-31 15:07
No problem. The app was open. Ich watched the message expire. The hourglass symbol started flashing and then just stopped. The message was not deleted. When I restarted the app (at 15:50) the message was gone.

**Comment by p4nci** [comment] 2016-11-01 08:50
It's a general problem:
Android (https://github.com/WhisperSystems/Signal-Android/issues/5790)
Desktop (https://github.com/WhisperSystems/Signal-Desktop/issues/950)

**Comment by riyapenn** [comment] 2016-11-17 06:08
Another Debug log: https://gist.github.com/anonymous/27700af215bf0301839a0dc5b54c8376
<img width="281" alt="screen shot 2016-11-16 at 10 06 06 pm" src="https://cloud.githubusercontent.com/assets/4898366/20378150/1153e41a-ac49-11e6-927a-83b107bda3d2.png">

**Comment by iadmir** [comment] 2016-11-28 17:12
I can confirm this behaviour on Signal for iOS, when I set timer to 30 minutes - 1 week expired messages are still there, messages gone only after restart. Didn't have this issue when I set timer to 5 seconds - 5 minutes.

**Comment by riyapenn** [comment] 2017-01-03 22:21
not disappearing on iOS: https://gist.github.com/anonymous/b21664c20e977a4920a3bc180ed14577 but disappearing on the desktop

**Comment by hodgesmr** [comment] 2017-04-21 18:02
Not sure if it's helpful for me to add to the pile, but I also generated a debug log for this problem: https://gist.github.com/anonymous/53fde209dc18eaabe56d009105384ec2

iOS app version 2.10.1. Messages set to disappear after 1 day. App remained in the background. After a day passed, messages did not vanish, but the hour glass icon pulsed for a few seconds.

Closing the app out of the app switcher and reopened; expected messages vanished.

**Comment by scottjacobsen** [comment] 2017-04-26 03:17
I'm seeing this with a 5 second expiration. The message doesn't disappear on iOS.

**Comment by TreatyOfRome** [comment] 2017-05-11 07:20
The 'disappearing messages' logic has been reworked in #2087. This might have fixed these problems?

**Comment by michaelkirk** [comment] 2017-06-14 19:41
Should have been fixed in 2.11. Please re-open if any of you have issues with messages not disappearing on time with iOS.

**Closed by michaelkirk** 2017-06-14 19:41 UTC

**Comment by wintonian** [comment] 2017-06-22 17:42
Messages are not disappearing in ver. 4.6.1 (android) without restarting the app. Timer appears to be stuck at 1 second remaining for all messages in a conversation that have expired.
