### ISSUE TITLE
'ProtocolBuffers.h' file not found

### ISSUE THREAD

**Issue by big-r81** [WhisperSystems/Signal-iOS#955] opened 2015-11-18 18:09 UTC
Hi,

after forking WhisperSystems/Signal-iOS and installing all pod files i get this
error after opening the workspace in Signal.
The project can't be build.

I get the following error:
/.../Signal-iOS/Signal/src/textsecure/Messages/IncomingPushMessageSignal.pb.h:3:9: 'ProtocolBuffers.h' file not found

What can I do, because this file is generated by the protocol buffer compiler?

Cherrs,
Ronny

**Comment by rygen** [comment] 2015-11-23 16:46
Hi,

Did you find any workaround meanwhile?
Yesterday I tried to build the project and had the same issue.

Cheers

**Comment by big-r81** [comment] 2015-11-23 17:36
Hi,

I tried to add some include paths but I had no luck...

Cheers

**Comment by rygen** [comment] 2015-11-23 17:48
Thanks for the update.

**Comment by mikeokner** [comment] 2015-11-23 23:36
The issue is due to a recent update to cocoapods. Should work if you downgrade like:

```shell
gem install cocoapods:0.38.2
```

**Comment by datesss** [comment] 2015-11-24 02:51
I followed the instruction in the git chat:
-Check out and follow instructions in BUILDING.md in the repo
-Open the workspace project file, not the Signal.xcodeproj file. The latter doesn't have all settings with regards to 3rd party libraries (pods)
-Replace "ProtocolBuffers.h" with "ProtocolBuffers/ProtocolBuffers.h""
-There will be a similar problem with openssl include (don't recall the name). Append "openssl/" i.e. "openssl/hmac.h"

Which resolved the issue with ProtocolBuffers.h, but now I'm getting a similar error in ContactsManager.h: "#import <Contacts/Contacts.h>  'Contacts/Contacts.h file not found'

this is my first time trying to contribute to an open source project so if i'm blatantly missing something sorry for taking up resources! thanks

**Comment by rygen** [comment] 2015-11-24 02:58
after following @mikeokner 's suggestion and downgrading to cocoapods:0.38.2 and opening the workspace project file, I was finally able to build and run on my test device. 
Have you tried the downgrade too @datesss ?

**Comment by datesss** [comment] 2015-11-24 04:42
My issue was that I needed to update XCode to get the 'Contacts' framework. 

`sudo gem install cocoapods:0.38.2`
resolved the issue with ProtocolBuffers.h, but not until I ran
`sudo gem uninstall`
to get rid of my older version.
 Thanks for your help!

**Comment by rygen** [comment] 2015-11-24 05:03
You could probably get away with just specifying the version you need: *pod _0.38.2_ setup* (http://stackoverflow.com/a/31772875/2829102). Nevertheless, I also did it like you and removed the newer version before I read that SO post :)

**Comment by rygen** [comment] 2015-11-24 17:58
Curiosity: Did you manage to get past the number verification screen when running the app?

**Comment by akatasonov** [comment] 2015-11-27 14:10
@rygen To get past the number verification screen you have to set up push notifications for your copy of Signal in your developer account

**Comment by rygen** [comment] 2015-11-27 18:56
@akatasonov thanks, solved!

**Comment by FredericJacobs** [comment] 2015-11-29 01:11
Fixed on master

**Closed by FredericJacobs** 2015-11-29 01:11 UTC
