### ISSUE TITLE
Aim for iOS 7.1 backward compatibility?

### ISSUE THREAD

**Issue by mro** [WhisperSystems/Signal-iOS#629] opened 2015-03-02 23:21 UTC
I know it may sound odd, aiming to support a device as old as the iPhone4, but it's about millions of devices out there in the wild which can't update to iOS 8.0.

How are you guys feeling about that?

**Comment by acoffman** [comment] 2015-03-02 23:39
This looks like a dupe of #614 and the answer seems to be "no."

**Comment by alex42ka** [comment] 2015-03-03 15:55
Would be really great. It's the most substantial argument against TextSecure as our main Messaging App at work.

**Comment by FredericJacobs** [comment] 2015-03-03 16:53
Discussion happens in #614

**Closed by FredericJacobs** 2015-03-03 16:53 UTC
