### ISSUE TITLE
Client failed 

### ISSUE THREAD

**Issue by tomeklew** [WhisperSystems/Signal-iOS#1118] opened 2016-03-17 12:40 UTC
Anyone knows how to fix it?

**Comment by tomeklew** [comment] 2016-03-17 12:42
https://gist.github.com/5cc6ade952470f4dc54a

**Comment by michaelkirk** [comment] 2016-03-17 15:06
dupe of #1115 

This is also affecting android, seems like a server side error and not specific to the iOS client.

**Comment by FredericJacobs** [comment] 2016-03-17 15:15
This was an infrastructure issue affecting Europe. Should be fixed now.

**Closed by FredericJacobs** 2016-03-17 15:15 UTC

**Comment by tomeklew** [comment] 2016-03-17 15:18
Thanks
