### ISSUE TITLE
Add share extension for Photos

### ISSUE THREAD

**Issue by metbril** [WhisperSystems/Signal-iOS#2148] opened 2017-05-24 04:24 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

There is a Share extension for the recently added attachments feature. Unfortunately I still can't share a photo from the iOS Photos app. Could you please add a share extension for photos?

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by NicolasCGN** [comment] 2017-05-24 11:43
I can also confirm it. Sharing photos is possible from Signal, but Signal doesn't show when trying to share a photo form the Photos app.

**Comment by macuser666** [comment] 2017-06-16 08:57
I can also confirm the absence of share extensions.
This is unfortunate, since without these extensions sharing files from within other apps is very cumbersome. 
Threema or Wire or Whattsapp support share extensions ...

**Comment by TreatyOfRome** [comment] 2017-07-19 07:10
This is a duplicate of open issue #650. This one can be closed?

**Comment by michaelkirk** [comment] 2017-07-19 12:49
closed as dupe of #650

**Closed by michaelkirk** 2017-07-19 12:49 UTC
