### ISSUE TITLE
Have an easy way to add an unknown number to iOS contacts

### ISSUE THREAD

**Issue by SimplGy** [WhisperSystems/Signal-iOS#1511] opened 2016-12-01 18:41 UTC
- [x] I have searched open and closed issues for duplicates

### Bug description

As a new user, I had one message from a friend who invited me. He was not in my phone contacts so the number was unknown.

To add to my contacts I had to memorize part of the number, switch apps, and repeat. Signal's privacy feature of masking the screen made peeking at the app in the background nonfunctional. Copy and paste was not available, nor any other feature for adding to contacts I could find.

### Steps to reproduce

1. With an unknown contact, open the conversation details.
2. Tap the header that shows the phone number. This will take you to contact details.
2. On the contact details screen, tap the large circle `(+)` button. This does nothing
3. On this contact details screen, tap and hold the phone number so you can copy the text. This text is not copyable.

**Actual result:** Plus button is not functional. Text is not copyable.

**Expected result:** Plus button should copy the phone number to your pasteboard or navigate you to iOS contacts with the phone number prefilled. Phone number text should be copyable ([x] user interaction enabled?)

### Device info

**Device**: iphone 6s+
**iOS version**: 9.3.2
**Signal version:** 2.6.6

**Comment by SimplGy** [comment] 2016-12-01 18:42
This would be a pretty trivial PR for me to do, looks like the project is a straightforward cocoapods setup -- would you like me to do this?

**Comment by michaelkirk** [comment] 2016-12-01 18:56
This is mostly a dupe of https://github.com/WhisperSystems/Signal-iOS/issues/1481, but I did pull out this new issue: https://github.com/WhisperSystems/Signal-iOS/issues/1512 based on your report, so thanks!

Bother are available to work on.

**Closed by michaelkirk** 2016-12-01 18:56 UTC
