### ISSUE TITLE
Verify the App Store binary is actually this code?

### ISSUE THREAD

**Issue by Meekohi** [WhisperSystems/Signal-iOS#705] opened 2015-03-12 13:54 UTC
Is there anyway to verify that the binary on the App Store actually corresponds to this codebase, and not some modified version?

**Comment by FredericJacobs** [comment] 2015-03-12 14:02
Duplicate of #641

**Closed by FredericJacobs** 2015-03-12 14:02 UTC

**Comment by Meekohi** [comment] 2015-03-12 14:17
Ah sorry, I looked around but didn't find that issue.
