### ISSUE TITLE
Lock screen preview settings.

### ISSUE THREAD

**Issue by acoffman** [WhisperSystems/Signal-iOS#631] opened 2015-03-02 23:55 UTC
Older issues (namely #272 and the issues that it links to) seem to suggest that message preview or at least sender names are available in the notification center/lock screen. Further, it seems to suggest that there are settings to configure this behavior. I don't see anything in the app or the general iOS settings page that allow users to enable this. Currently, I just see "You have a new message" rather than the sender name. Was this feature removed prior to shipping the 2.0 release? Is it expected to return?

A minor inconvenience in what is an otherwise incredible app. Thanks for all the hard work on this!

**Comment by karlhedderich** [comment] 2015-03-03 00:58
I would like to see this feature too :)

Great Job btw!!

**Comment by konklone** [comment] 2015-03-04 20:09
As a note, the lack of preview on lock screen is causing some friends of mine to rule out the use of Signal as their primary texting app. Other issues suggest this support was in there at one time -- is it possible to get the text of messages popping up on the lock screen?

**Comment by FredericJacobs** [comment] 2015-03-04 22:43
Duplicate of #643

**Closed by FredericJacobs** 2015-03-04 22:43 UTC

**Comment by konklone** [comment] 2015-03-04 22:51
Can you explain how that's a duplicate? #643 doesn't discuss whether the contents of received messages should be displayed on the lock screen.

**Comment by konklone** [comment] 2015-03-04 22:52
If that _is_ what #643 is about, and you're saying that it's difficult to display the text of notifications on the lock screen in a safe way, I encourage you to write up why -- and I also encourage you to work very hard on ways to change that. The inability to read the text of messages on the lockscreen is literally driving my friends away from Signal, and back to the default messaging app. The Android app does not have these limitations.

**Comment by FredericJacobs** [comment] 2015-03-04 23:01
Android is a very different platform. Trust me, I've desperately tried all available APIs to do background decryption of messages and it's just not working reliably. More detailed writeup coming soon.

**Comment by konklone** [comment] 2015-03-04 23:15
Instead of a detailed writeup of why it won't work, could we channel it first into a quick call for help by other iOS people and cryptographers? The WhisperSystems mantra is, fundamentally, about demonstrating that you do not have to give up UX to get security and privacy, and overcoming whatever hurdles it takes to get there.

While my experiences so far are anecdotal, if Signal for iOS can't compete with the default Messaging app on a fundamental piece of UX -- that adds friction every single time someone receives a message, in comparison to what they were used to -- I think it will keep a real ceiling on Signal adoption outside of committed privacy folks.

**Comment by FredericJacobs** [comment] 2015-03-05 09:51
The only actor that can change something is Apple and I'm already discussing that with them.

**Comment by konklone** [comment] 2015-03-05 20:56
Very glad to hear it! Since it sounds like that would require an OS point fix, one thing you might consider as an interim measure is allowing the unsafe decryption to be performed, and the text of the notification shown, as an opt-in setting for those who are comfortable making that tradeoff.

**Comment by konklone** [comment] 2015-03-05 20:59
> one thing you might consider as an interim measure is allowing the unsafe decryption to be performed, and the text of the notification shown, as an opt-in setting for those who are comfortable making that tradeoff.

Though, talking that through, I understand that implicates the sender's consent as well, which might make this tougher. That's frustrating.
