### ISSUE TITLE
Group conversations muting

### ISSUE THREAD

**Issue by bobberb** [WhisperSystems/Signal-iOS#853] opened 2015-07-14 22:03 UTC
Currently available on textsecure for android, group conversations can be muted.

In addition, like facebook, muting for a specified interval would be lovely.

**Comment by FredericJacobs** [comment] 2015-07-17 19:24
Agreed, this is necessary but unfortunately not really easy to make happen given the fact that Signal has no guaranteed background running time which is crucial to make this feature happen due to end-to-end encryption. But we're working on it!

**Comment by bobberb** [comment] 2015-07-17 22:17
Do apps like WhatsApp and Telegram also get denied this background process?

**Comment by FredericJacobs** [comment] 2015-07-17 23:52
Telegram doesn't have encrypted groups so they don't have that issue since the server keeps track of your groups and which ones you muted.

**Comment by 2-4601** [comment] 2015-12-10 15:05
I guess this is a duplicate of #346 now since it was reopened.

**Closed** 2015-12-10 22:18 UTC
