### ISSUE TITLE
Multi device support now we have the desktop client?

### ISSUE THREAD

**Issue by mahyar** [WhisperSystems/Signal-iOS#1473] opened 2016-11-17 09:29 UTC
Now we have the desktop client, what would it take to add multi-device support for the same account?  I'm guessing it would a similar mechanism as the desktop client?  It would be great for iPad users.

**Comment by 2-4601** [comment] 2016-11-17 15:09
Duplicate of [#823](https://github.com/WhisperSystems/Signal-iOS/issues/823#issuecomment-253118382).

**Closed** 2016-11-17 15:16 UTC
