### ISSUE TITLE
No horizontal Layout

### ISSUE THREAD

**Issue by astronouth7303** [WhisperSystems/Signal-iOS#1476] opened 2016-11-17 22:14 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
No horizontal layout

### Steps to reproduce
1. Open signal
2. Unlock screen orientation (if locked)
3. Turn phone sideways

**Actual result:** I see signal sideways
**Expected result:** Signal to rotate into a horizontal layout

### Device info

**Device**: iPhone 6
**iOS version**: 10.1.1
**Signal version:** 2.6.4

**Comment by michaelkirk** [comment] 2016-11-17 22:15
dupe of https://github.com/WhisperSystems/Signal-iOS/issues/937

**Closed by michaelkirk** 2016-11-17 22:15 UTC
