### ISSUE TITLE
Difficult to differentiate different members in a group

### ISSUE THREAD

**Issue by trstnthms** [WhisperSystems/Signal-iOS#779] opened 2015-05-05 12:53 UTC
When multiple people are messaging within a group, it is difficult to differentiate between each individual person's messages. iMessage and Telegram both solve this quite nicely with the person's picture/first letter of first name next to their messages.

**Comment by riyapenn** [comment] 2015-08-13 01:05
https://github.com/WhisperSystems/Signal-iOS/issues/736

**Comment by michaelkirk** [comment] 2016-04-12 12:56
closing (dupe of #736)

**Closed by michaelkirk** 2016-04-12 12:56 UTC
