### ISSUE TITLE
Attaching image immediately sends message.

### ISSUE THREAD

**Issue by nanotechz9l** [WhisperSystems/Signal-iOS#1020] opened 2015-12-21 06:39 UTC
Current operation:

1. Create new thread or add text to an existing one.

2. Attach image/select from library. As soon as an image is selected the message is sent ignoring the previous added text in step one.

Current work around is to press send in order to send the originally ignored text. That leaves the recipient to receive the image first and text second.

Expected result:
Attaching an image should not send the message immediately. After the user attaches an image it should be added to the bottom of the mesage with message text on top / pix on bottom.

**Comment by FredericJacobs** [comment] 2015-12-21 14:23
This is a duplicate of #858.

Please review existing issues before opening new ones, thanks.

**Closed by FredericJacobs** 2015-12-21 14:23 UTC

**Comment by nanotechz9l** [comment] 2015-12-22 06:22
Understood but its alot of issues to go thru via mobile. When a user reports an issue/bug the devs should be thankful to receive it. Expecting a user to troll thru all open/closed tix is time consuming. Keyword search function would be nice.

**Comment by JohanDoe** [comment] 2015-12-22 08:09
@nanotechz9l keyword search function exists. 

![screen shot 2015-12-22 at 09 06 00](https://cloud.githubusercontent.com/assets/10408552/11950751/8ccbdea8-a88b-11e5-91d1-64565af05cd0.png)

Dev spends a lot of time coding, and doing issue management. It's a small request to search for existing issues on same topic to help them. Keeps everybody efficient and happy!

Cheers.

**Comment by nanotechz9l** [comment] 2015-12-23 08:14
Def understood that were all busy. My original reply above indicated that on a mobile device filters are not available. Im a signal ios user so I create all issues via mobile.
