### ISSUE TITLE
No Dynamic Type support

### ISSUE THREAD

**Issue by tasoili** [WhisperSystems/Signal-iOS#798] opened 2015-05-27 06:42 UTC
If I increase the font size in Display & Brightness/Text Size (or under Accessibility), Signal continues to show with its default font size.

Is there any chance dynamic type could be supported?

**Comment by FredericJacobs** [comment] 2015-05-27 10:03
Duplicate of work in progress #471

**Closed by FredericJacobs** 2015-05-27 10:03 UTC
