### ISSUE TITLE
show all images in conversation

### ISSUE THREAD

**Issue by maximiliankaul** [WhisperSystems/Signal-iOS#961] opened 2015-11-21 15:50 UTC
Hi,
(I have no idea how to tag this as feature request so I'm posting it as an issue.)
the iOS App doesn't seem to have an option to show all images in a conversation. This option is available on Android and also with WhatsApp and it is a reason why I'm having a hard time to convince some of my friends to use Signal instead of WhatsApp.
Pleas think about implementing this feature.
Thank you

**Comment by mmkassem** [comment] 2015-11-23 03:22
Duplicate of #349

**Closed** 2015-11-23 07:12 UTC
