### ISSUE TITLE
Password Locking

### ISSUE THREAD

**Issue by BenMorganIO** [WhisperSystems/Signal-iOS#1552] opened 2016-12-16 18:14 UTC
Hey guys,

I'm dealing with a threat right now where a mother is going through their adult children messages with their partners. As one can expect, these are some private messages. I'm cringing at the thought that this was through Signal.

Are we able to get Signal password protected for family feud threat models? This way messages can stay between individuals and not accidentally leak to their immediate circle.

**Comment by michaelkirk** [comment] 2016-12-16 18:21
dupe of #738 

If it's their personal phone, suggest that they lock their phone with a secure password/pin.

**Comment by BenMorganIO** [comment] 2016-12-16 18:21
@michaelkirk yes, but if your mother asks to play solitaire on your iPad, what would you do?

**Closed by michaelkirk** 2016-12-16 18:21 UTC

**Comment by BenMorganIO** [comment] 2016-12-16 18:24
Also, wasn't a phone, was an iPad.
