### ISSUE TITLE
Need to pause after enabling video call for setting to take effect

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1774] opened 2017-02-15 22:07 UTC
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
After enabling video call, user needs to wait before toggling out of Settings for new audio/video calling to be enabled

### Steps to reproduce
- Enable video calls
- Quickly go "back" leaving Advanced Settings Screen
- Go back to Advanced

**Actual result:** See video calling has not been enabled
**Expected result:** Video calling is enabled and CallKit option displayed immediately before user goes back

### Device info

**Device**: iPhone SE, iPhone 5S
**iOS version**: 10.2.1
**Signal version:** 2.7

### Link to debug log

https://gist.github.com/209991c0722db43ceaed790424cf7f1b this log currently doesn't show user on Signal 2.7 though :(

**Comment by riyapenn** [comment] 2017-02-16 18:28
Another user where enabling video calling doesn't stick even after pausing: https://gist.github.com/1fbbd69aae4df5695fda2ed54bd7c580 this log current doesn't show the user on Signal 2.7 either :(

**Comment by charlesmchen** [comment] 2017-02-16 19:09
Closing as a dupe of #1776

**Closed by charlesmchen** 2017-02-16 19:09 UTC
