### ISSUE TITLE
Sigal iOS9 iPhone 4s causes very high mobile data use! 

### ISSUE THREAD

**Issue by r100gs** [WhisperSystems/Signal-iOS#1043] opened 2016-01-14 18:32 UTC
Hey guyes,

Iam using Signal on my iPhone 4s with iOS and it caused 775MB of mobile internet data within 13. days! I wrote arround 5 txt messages to others without any pictures or video! What can I do?

**Comment by 2-4601** [comment] 2016-01-14 22:36
This is a duplicate of #866.

**Closed** 2016-01-20 00:44 UTC
