### ISSUE TITLE
Progress indicator for attachment uploading

### ISSUE THREAD

**Issue by corbett** [WhisperSystems/Signal-iOS#440] opened 2015-01-21 09:46 UTC
- [x] Queuing visual enhancement
- [ ] Progress indicator

**Comment by vingtdeux** [comment] 2015-03-04 03:27
I was about to open an issue (attachment failures due to lack of connectivity give no feedback), but I'm wondering whether it's already handled under this one?

1. Tapped the paperclip
2. Selected "Choose from Library..."
3. Navigated to a photo, selected it
4. The photo disappeared, returning me to the chat view, but nothing else happened
5. Waited, thinking there might be some delay
6. Repeated 1-5, then realized that my service had dropped out
7. Returned to an area with connectivity, verified that nothing showed up.

I was able to reproduce this repeatedly in Airplane Mode. Text sent while offline appears greyed out, indicating that it wasn't sent (tapping there gives the option to resend). It would be great to have similar functionality for attachments, or at least an error in the style of "The user is not registered."

Thanks (for all of this... I'm so excited to finally have messaging capabilities)!

**Comment by jackflips** [comment] 2015-03-24 07:20
Is this being worked on currently? If not I'm happy to have it assigned to me.

**Comment by chchen** [comment] 2015-03-30 20:00
Yeah, people trying to send me attachments are frustrated because there's no feedback if the uploading fails.

See https://gist.github.com/anonymous/198e7e70531f2ad71a32

**Comment by anatoli26** [comment] 2017-02-18 04:56
Attachments downloading/uploading is not working correctly. Any ETA on this? What help is wanted? Please give a progress on this critical issue.

**Comment by michaelkirk** [comment] 2017-02-18 16:04
Can you offer any details beyond "not working"? 

Does it never work? Does it work sometimes? When? Thanks.

What were you doing when it didn't work? What did you see? What did you expect to see?

A debug log and the time in the log that corresponds to the behavior you saw will also help.

Thanks for working with us to get this fixed.

**Comment by anatoli26** [comment] 2017-02-18 16:33
> Can you offer any details beyond "not working"?

Most problems are already mentioned in this issue and in the related/linked ones. Personally (in my own experience and of my group of contacts who installed Signal because I insisted), I find the following problems:
 - no indicator of download/upload progress so one can't estimate nor see what's going on, if there's any progress, etc. For large attachments or poor connection this is critical.
 - "attachment is downloading" for eternity happens from time to time, no way to retransmit the message and the peer who sent it doesn't know I didn't get it. Knowing that, when I send something, I should ask for confirmation every time just to be sure my contacts get what I send them. And if they didn't get it, for a voice message I should record it again.

The overall situation with media transmission is quite frustrating, my contacts say: I'll send it via wapp/Telegram, and I have to agree.

**Comment by TreatyOfRome** [comment] 2017-04-06 07:07
Issue could be closed? Upload progress bar has been added with  #1849 and #1891? Present in Signal 2.9.0.
Or the issue's title should be changed to _download_ indicator?

**Comment by anatoli26** [comment] 2017-04-06 12:31
For me the "attachment is downloading" for eternity is still there. Still receiving photos that never download. This is critical. Ideally, from the UX PoV there should be some download progress indicator and from the dev PoV, there should be a short timeout and multiple automatic retries so the app tries again and again to download the attachment and if there's a permanent error, such condition should be communicated to the user.

**Comment by TreatyOfRome** [comment] 2017-04-06 12:41
@anatoli26 you mean something like #1907? Looks like this PR has been merged for Signal 2.10.0.

**Comment by anatoli26** [comment] 2017-04-06 12:53
@TreatyOfRome, thanks for the update. This will probably fix the issue to at least being able to retry the failed downloads manually. I'll comment on its effectiveness when 2.10 is published.

**Comment by michaelkirk** [comment] 2017-04-06 14:40
Thanks @TreatyOfRome, you're right. Upload progress indicator was merged.

**Closed by michaelkirk** 2017-04-06 14:40 UTC
Labels: In PR

**Comment by anatoli26** [comment] 2017-04-11 03:15
I can confirm that the newly released v2.10 has fixed the problem of eternal "attachment is downloading", though there's no indicator of the download progress, nor any information about the total size of the attachment, so one doesn't know if it's a small photo or a huge video, so can't estimate the download time. It would be great to show a total size and a progress indicator with already downloaded size.

**Comment by michaelkirk** [comment] 2017-04-11 13:19
Could you open a separate issue?

**Comment by anatoli26** [comment] 2017-04-11 13:52
#1969
