### ISSUE TITLE
Force Touch causes force close

### ISSUE THREAD

**Issue by StrongGoat** [WhisperSystems/Signal-iOS#1100] opened 2016-03-07 17:04 UTC
From a fresh install, with no contacts or messages, Force Touch the main message area (still says start your first Signal conversation!).  Result: app force closes every time.  Iphone 6s+, iOS 9.2.1.  Log here, but there isn't anything interesting: https://gist.github.com/anonymous/3c9f0f3011b59520859b

**Comment by 2-4601** [comment] 2016-03-07 17:10
Duplicate of #990.

**Comment by StrongGoat** [comment] 2016-03-07 17:32
#990 is a long press issue.  I cannot replicate the issue with long press on my system.

**Comment by 2-4601** [comment] 2016-03-07 17:35
#1044 is a force touch issue which was closed as a dupe of #990 by the developer.

**Comment by StrongGoat** [comment] 2016-03-07 17:45
Then someone should update #990

**Comment by michaelkirk** [comment] 2016-05-07 16:40
reported as fixed in HEAD by @riyapenn 🎉

**Closed by michaelkirk** 2016-05-07 16:40 UTC
Labels: crash
