### ISSUE TITLE
We should support paste of image, video, audio files.

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1746] opened 2017-02-11 02:33 UTC

**Comment by michaelkirk** [comment] 2017-02-13 14:06
related to https://github.com/WhisperSystems/Signal-iOS/issues/1132

**Comment by michaelkirk** [comment] 2017-02-13 14:09
partial dupe of https://github.com/WhisperSystems/Signal-iOS/issues/793

**Comment by michaelkirk** [comment] 2017-04-03 17:58
solved in 2.9

**Closed by michaelkirk** 2017-04-03 17:58 UTC
