### ISSUE TITLE
Missing nb_NO transl for placeholder text in new message 

### ISSUE THREAD

**Issue by byeskille** [WhisperSystems/Signal-iOS#1212] opened 2016-06-12 15:53 UTC
- [ x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When viewing a chat dialogue with a contact the placeholder text in the composer for a new message is not translated to Norwegian. 

The text will be shown in English as "New Message" even if the phone is set to Norwegian (Norsk bokmål). The rest of the app is translated correctly, and the placeholder text is changed to German if I change the phone to German.

I participated in the translations and it seems to be correct in Transifex, and even in this file in the repo:
[nb_NO.lproj/Localizable.strings](https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/translations/nb_NO.lproj/Localizable.strings)
on line 224
defined as `MESSAGE_COMPOSEVIEW_TITLE`

### Steps to reproduce
- set iOS to Norwegian language (Norsk bokmål, nb_NO)
- open Signal for iOS
- open a chat dialogue with a contact
- confirm the placeholder text in the message composer is not translated and shows the English text "New Message"

**Actual result:** The placeholder text shows: New Message
**Expected result:** The placeholder text should have shown: Ny melding

### Screenshots
![signal-send-message](https://cloud.githubusercontent.com/assets/11771452/15992125/d1428808-30c5-11e6-805d-8d3e0bbdf8bc.JPG)

### Device info

**Device**: iPhone 6
**iOS version**: 9.3.2
**Signal version:** 2.3.1 beta

**Comment by byeskille** [comment] 2016-06-12 16:15
Update:
It might be connected to this issue earlier experienced with Finnish: #784

**Comment by 2-4601** [comment] 2016-06-12 19:04
This is actually a duplicate of #1062.

**Comment by byeskille** [comment] 2016-06-12 20:02
OK!

It seems some other Norwegian already have written a pull request with the necessary strings:
[JSQMessagesViewController/pull/1564](https://github.com/jessesquires/JSQMessagesViewController/pull/1564)

So I guess Signal will get it when you update your version of the code?

But for some reason it is called [nb.lproj/JSQMessages.strings](https://github.com/jessesquires/JSQMessagesViewController/blob/release_7.3/JSQMessagesViewController/Assets/JSQMessagesAssets.bundle/nb.lproj/JSQMessages.strings) and not nb_NO

Does this affect the usage in Signal?

**Comment by michaelkirk** [comment] 2016-06-13 18:49
@byeskille - we are on our own fork of JSQMessageController, so it's not quite as simple as just pulling in the latest upstream code.

Closing as a dupe of #1062

**Closed by michaelkirk** 2016-06-13 18:49 UTC
