### ISSUE TITLE
Tap & tap-and-hold on contact's name occasionally not working

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-iOS#788] opened 2015-05-22 21:57 UTC
I have tried the fingerprint verification screen on three of my friends' iPhones: 4S, 5 and 5S.
4S and 5S work as expected but for some reason on the **iPhone 5** the screen does not show up.
More specifically when in a conversation and I:
- tap the the contact's name the phone number does not show up
- tap and hold the contact's name the fingerprint screen does not show up

In both cases basically nothing happens. The name does not react to any touches.

In this specific device there are two Signal contacts. One of them is **only** a RedPhone user so I would assume the fingerprint screen would not work since there's no long-term key like there's in TextSecure. But the other contact (me) is both a RedPhone and a TextSecure user and the fingerprint screen should work - yet it does not.

More details:
- Signal was first installed on this device in fall 2014 i.e. 1.x version
- The user's own fingerprint is visible and copyable in the settings
- Texts and calls work normal
- Signal 2.0.3, iPhone 5, iOS 8.3
- This was not tested prior 2.0.3

I understand this is hard to fix since it's reproducible only on a single device/install.
Would the tap and long-press on the contact's name show in a debug log? I could post it next time I see my friend in person.

Thanks.

**Comment by FredericJacobs** [comment] 2015-05-23 09:13
Is the contact's name really short? might be that it makes it to hard to tap on?

**Comment by 2-4601** [comment] 2015-05-23 10:19
Nope. It's 10 characters long (space not included)

**Comment by FredericJacobs** [comment] 2015-05-24 21:14
Looked through the code but I must say that I'm a little lost about what to do here.

I'm unable to reproduce :(

**Comment by 2-4601** [comment] 2015-05-24 21:17
Thanks for looking into this.

Would this show in a debug log?

If not I'll just advice a reinstall.

**Comment by FredericJacobs** [comment] 2015-05-24 21:21
I honestly don't see how a reinstall would help. Nothing in the state of the application would influence this.

Have you tried with different names?

**Comment by 2-4601** [comment] 2015-05-24 21:27
There's only one other contact and that contact is RedPhone only, so we have not been able to try with other names.

The name with the issue works in two other Signal installs without problems. It's an ascii only, 5 letters first name, 5 letters surname.

Could iOS contact restrictions affect this?

I will try with different names the next time I see my friend (need to introduce other Signal users for that).

**Comment by 2-4601** [comment] 2015-07-03 18:27
I experienced this today with another device: iPhone 4S, iOS 8.3, Signal 2.1.1

All the contact names had this issue: no reaction to either tap nor tap and hold
I tried changing the contact names but it did not help.

I used the in-app submit debug log feature twice but it just caught a failure to submit the debug log itself: :) [1](https://gist.github.com/anonymous/35c9ab732ceb17827186), [2](https://gist.github.com/anonymous/4cff745c119f6be61992) (btw the submit process has untranslatable strings)

The issue got fixed after swipe-killing from the app switcher and restarting Signal.

**Comment by rianhunter** [comment] 2016-02-02 19:01
+1 on this issue. I have experienced this multiple times. #1066

My theory is a misused UI component that causes the tap handler to stop being invoked after some UI hierarchy change, e.g. Opening the image send dialog (but not that).

Will try to get concrete reproducibility steps.

**Comment by zyphlar** [comment] 2016-04-06 04:40
Experiencing this issue for only one contact, which was an Android/Redphone user before they upgraded to Signal Android. iPhone 5s running iOS 9.3.1.

**Comment by michaelkirk** [comment] 2016-09-19 21:07
Is this still reproducible for anyone on a current build?

**Comment by riyapenn** [comment] 2016-12-09 00:06
Closing as #1402 covers this issue with more recent user flow.

**Closed by riyapenn** 2016-12-09 00:06 UTC
