### ISSUE TITLE
UX issues of creating new groups

### ISSUE THREAD

**Issue by mrphs** [WhisperSystems/Signal-iOS#1526] opened 2016-12-05 06:54 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When you finally manage to find the button to create a group, and while going through your list to add members, it's very easy to make a mistake and add the wrong person to the group as an accidental tap would add them and there's no indication of how many people you've selected and who those people are.

Lack of having a search box to find and add people, adds up to the issue.

### Steps to reproduce
- tap on group button
- tap on the names of a couple of random contacts
- scroll some more down and see how you wont know who you've added to the list 

**Actual result:** You'd have to check, {double, triple} check your whole contact list carefully to make sure you didn't tap on any wrong names. 
**Expected result:** have a search box to filter names out and select ones that you want to be added. and have an indicator on top of the list about who has been added. This indicator can be simply just sticking the added names to the top, or just showing their name or even showing a number or the added people. or could be a mix of all above.
Something like:
[Alex B] [Jane T] [Sandra T] in separate gray boxes on top, and if they exceed the width of the display, they could start showing a number of total. These are some ideas that just crossed my mind.. or you could just redesign the UI of this section to make it a bit more smooth. 

### Device info
**Device**: iPhone
**iOS version**: 10.1.1
**Signal version:** 2.6.6

**Comment by michaelkirk** [comment] 2016-12-05 14:21
Partial dupe of #669.

**Comment by michaelkirk** [comment] 2017-10-16 21:52
Since we now show which members you've selected, and allow you to unselect them when creating the group, the remaining functionality in this request is a dupe of #669

**Closed by michaelkirk** 2017-10-16 21:52 UTC
Labels: needs design
