### ISSUE TITLE
[Feature request] iPad/iPod Linked Support

### ISSUE THREAD

**Issue by trymeouteh** [WhisperSystems/Signal-iOS#2810] opened 2017-11-25 22:16 UTC
With the desktop version being a stand-alone which links to your phone a cool feature would be to allow your iPad/iPod which don't support a SIM card to allow it to be linked to your phone just like the Desktop versions. Same can go with Android Tablets.

**Comment by NinebitX** [comment] 2017-11-26 18:42
Duplicate of https://github.com/WhisperSystems/Signal-iOS/issues/823.

**Comment by michaelkirk** [comment] 2017-11-27 17:22
closing as dupe of #823

**Closed by michaelkirk** 2017-11-27 17:22 UTC
