### ISSUE TITLE
Support Sending Voice Messages

### ISSUE THREAD

**Issue by ngheungyu** [WhisperSystems/Signal-iOS#1395] opened 2016-10-15 10:11 UTC
- [ x] I have searched open and closed issues for duplicates

---

It'd be great to have the support to send voice messages like other messengers do. Thanks

**Comment by RiseT** [comment] 2016-10-25 23:08
@michaelkirk Don't know if you're aware of it, but just to be sure: In Signal Android, this already has been implemented some time ago. It just has been commented out, waiting for Signal iOS:

https://github.com/WhisperSystems/Signal-Android/commit/885fc88aad2b45822bfd9734012b76a36355443f

**Comment by michaelkirk** [comment] 2016-10-25 23:26
@RiseT - Yup! On the roadmap.

**Comment by rainerzufall** [comment] 2016-11-29 11:54
dupe of #230?

**Comment by michaelkirk** [comment] 2016-11-29 21:25
Closing this as dupe of #230.

**Closed by michaelkirk** 2016-11-29 21:25 UTC
