### ISSUE TITLE
alternative athentication to sms

### ISSUE THREAD

**Issue by vv01f** [WhisperSystems/Signal-iOS#647] opened 2015-03-03 16:02 UTC
There are devices intentionally not connectable via SIM and thus not enabled for SMS.
It would be nice to have an alternative authentication and identifier than the phone number.
This is also a privacy issue as phone numbers can easily tried and servers cannot be trusted.
This also can be a step for enabling "web-clients" as well as multiple devices for one account.

**Comment by FredericJacobs** [comment] 2015-03-04 22:39
Duplicate of #83

**Closed by FredericJacobs** 2015-03-04 22:39 UTC
