### ISSUE TITLE
Can't paste images

### ISSUE THREAD

**Issue by hubert3** [WhisperSystems/Signal-iOS#793] opened 2015-05-25 06:19 UTC
Signal 2.0.3 on iPhone 6 iOS 8.3

I can paste text from the clipboard but when I copy an image from within Signal or Photos, then attempt to paste in a Signal conversation by tapping and holding on the text entry field, "Paste" does not appear as an option.

**Comment by hubert3** [comment] 2015-06-10 15:39
Unchanged in 2.1.50

**Comment by breadtk** [comment] 2015-06-16 16:22
:+1: 

The ability to paste in images would be fantastic! As it stands right now you have to save the image into your Camera Roll and then pull it up through the library. This adds (potentially) an unnecessary fleeting image into your library. Also, cats.
![Private Investocat](https://octodex.github.com/images/privateinvestocat.jpg)

**Comment by platypus5021** [comment] 2015-11-12 19:36
Has there been any traction on this issue? To be able to paste text, but not images doesn't make any sense.

**Comment by breadtk** [comment] 2015-11-12 21:27
cc @FredericJacobs

**Comment by platypus5021** [comment] 2015-12-01 16:56
Doesn't seem to be any developer action on this thread. Not flagged with any labels eithers. Can I safely assume that it's wishful thinking on my part that this function will be included in the future?

**Comment by FredericJacobs** [comment] 2015-12-01 17:17
@platypus5021 : Waiting for your pull request!

**Comment by platypus5021** [comment] 2015-12-01 17:33
Oh boy. I am not a coder by any stretch of the imagination!

@hubert3? @breadtk?

**Comment by FredericJacobs** [comment] 2015-12-01 17:50
It's something that's being worked on but we'll need a few more weeks to get it done since higher priorities items are on the list.

**Comment by mikeokner** [comment] 2016-01-07 04:25
I've been looking into implementing this. Looks like there's a relatively straightforward hook for it mentioned in jessesquires/JSQMessagesViewController#1345, but WhisperSystems/JSQMessagesViewController is out-of-date and doesn't implement that.

I'll play around and see how much of a pain it is to merge in the latest version of jessesquires/JSQMessagesViewController to WhisperSystems/JSQMessagesViewController.

**Comment by NHDaly** [comment] 2016-11-27 21:12
To add another perspective to this issue, many keyboards now work using this copy/paste images model.

- Bitmoji works by providing a keyboard where you scroll through your bitmoji images (images of your avatar doing things) and when you tap one it says "Copied to your clipboard." However, then tapping on the text box doesn't bring up the `Paste` button like it would in another messaging app (iMessage or Wh****pp).

- Google's GBoard works similarly by allowing you to copy/paste an image of your search result "card" displaying, as an example, a map of your search result's location.


My friend who has an iPhone was saddened by this when I had her switch to Signal this weekend.

**Comment by NHDaly** [comment] 2016-11-27 21:29
Is this now a dupe of #1407?

**Comment by michaelkirk** [comment] 2016-11-28 14:43
> Is this now a dupe of jessesquires/JSQMessagesViewController#1407?

Maybe related, but not a dupe. Apart from whatever needs to be done in JSQMVC, there is design work that needs to be done in Signal for pasting images to make sense.

One approach would be like iMessage where one just pastes the image(s) into the text field, however the other Signal clients are centered around a "image+caption" design, meaning only one image per message, which has an optional message that appears *after* the image.

More likely, we'd follow the existing clients lead and build the interface to respect the media+caption approach.

**Comment by mikeokner** [comment] 2016-11-28 16:28
FWIW it's been quite a while since I looked into this, but it looked like it was going to be a pretty big pain to update JSQMVC. The OWS fork has quite a few modifications for phone features that need to be sorted through.

**Comment by michaelkirk** [comment] 2016-11-28 16:43
>  it looked like it was going to be a pretty big pain to update JSQMVC

You are correct. It was a big pain. But it's done now. =)

**Comment by NHDaly** [comment] 2016-12-05 02:37
> More likely, we'd follow the existing clients lead and build the interface to respect the media+caption approach.

As long as you can paste directly into the text field, i think users will be happy with any design.

> You are correct. It was a big pain. But it's done now. =)

Cool! :)

**Comment by andreaatavoxi** [comment] 2017-01-23 01:24
As NHDaly said, this user would be very happy to be able to paste a clipboard image into the text box and be able to send that image regardless of whether I can add a caption or not.

**Comment by MrAlexWeber** [comment] 2017-01-26 19:38
Hi all, Signal user here, looking into this issue as I often paste GIFs into my chats in iMessage.
@michaelkirk said:

> One approach would be like iMessage where one just pastes the image(s) into the text field

This seems like a good idea to me, as it wouldn't require a redesign of the message sending UI, and would mimic existing iOS functionality. If the underlying technical issues have been sorted out by @NHDaly, maybe this choice could get this requested feature out sooner!

Thanks for reading and consideration.

**Comment by michaelkirk** [comment] 2017-01-26 19:55
>> One approach would be like iMessage where one just pastes the image(s) into the text field

I want to qualify that suggestion...

Currently on Signal-iOS you can send text *or* media, but you cannot send text *with* media. Signal-Desktop and Signal-Android both support text+attachment, but with some limitations vs. how the iMessage interface works.

Namely:
1. Only one attachment
2. Text goes below the attachment.

e.g. here's the compose interface on Signal-Desktop with an attachment and text.

![screen shot 2017-01-26 at 2 48 15 pm](https://cloud.githubusercontent.com/assets/217057/22347627/a81c5034-e3d6-11e6-82e6-1cb0f64906f9.png)

So, the UX for this feature might be untenable without first implementing an interface that allows text+attachments (#1132).

If you do want to proceed, start with a design proposal please to make sure we're on the same page.

**Comment by NHDaly** [comment] 2017-01-26 19:57
> If the underlying technical issues have been sorted out by @NHDaly, maybe this choice could get this requested feature out sooner!

(Just want to clarify that I haven't done any sorting of technical issues at all! 😁 ) I am merely a lowly +1 monger)

**Comment by NHDaly** [comment] 2017-01-26 20:00
Also, to support @michaelkirk's point, here's how it looks on android:

![screenshot_20170126-135850](https://cloud.githubusercontent.com/assets/1582097/22348024/bf46c7f0-e3cf-11e6-8363-04847a83cf7a.png)


Notably, the "attach" button disappears after attaching an image, so it's not possible to attach more than one image.

**Comment by jm3** [comment] 2017-03-21 03:42
This issue is tagged with `#needsdesign`. I'd like to volunteer to help with design / spec if it will help nudge this forward in the queue.

**Comment by charlesmchen** [comment] 2017-03-21 13:36
Image paste (along with audio and video) has been added and will ship in v2.9.0.

**Closed by charlesmchen** 2017-03-21 13:36 UTC
Labels: needs design

**Comment by NHDaly** [comment] 2017-03-28 00:43
v2.9.0.?

It looks like we're on v2.9.0.5 now? Did you mean v2.9.0.6? 😄  Thanks!

**Comment by mikeokner** [comment] 2017-03-28 02:06
2.8.3 is the latest release on the app store. I believe the changes were merged in #1834.

**Comment by charlesmchen** [comment] 2017-03-28 13:31
@mikeokner @NHDaly We've just release v2.9.0.5 which includes paste.  During testing we discovered a bug in copying images on iOS 9, which will be fixed in the next release.

**Comment by andreaatavoxi** [comment] 2017-03-28 13:53
It' is working wonderfully well for my purposes. Thank you!!

**Comment by jm3** [comment] 2017-03-28 18:14
@mikeokner @charlesmchen where should we look to learn when e.g. release v2.9.0.5 (or any other future release) is scheduled to be in the app store?

**Comment by charlesmchen** [comment] 2017-03-28 19:16
@jm3 We try to release every two weeks or so.  So, any work that we say will ship in the next release will ship within a few weeks.

**Comment by NHDaly** [comment] 2017-03-28 21:24
That's awesome.

Thanks again for your quick work implementing this!! 😄

**Comment by jdcrunchman** [comment] 2017-12-05 23:04
I so need the ability to paste pictures into Signal.    When will this app be upgraded again?

**Comment by MrAlexWeber** [comment] 2017-12-05 23:07
@jdcrunchman it's possible to paste images in the current iOS version of Signal. If you can't, you should probably consider opening a separate bug.
