### ISSUE TITLE
Remember last used keyboard language for each individual chat

### ISSUE THREAD

**Issue by likyng** [WhisperSystems/Signal-iOS#1284] opened 2016-07-21 17:16 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
The keyboard language is not remebered for each chat. That behaviour is expected (by me) and very useful if chatting in different language with different friends. Other applications such as Facebook Messenger also have that behaviour.

### Steps to reproduce
- open a chat with a person
- select e.g. the english keyboard and chat with that person
- select a different chat and change the keyboard language
- if you go back to chat nr. 1 the keyboard language will be that of chat nr. 2

**Actual result:** The keyboard language in a chat is set to whatever was used right before the chat was entered.
**Expected result:** In case of a new chat, the last used keyboard language is used (current behaviour). For any existing chat, the last keyboard language used in that chat should be used. If the last used keyboard was the emoji keyboard, return to the keyboard language used before that.

### Device info
**Device**: iPhone 6
**iOS version**: 9.3.1
**Signal version:** 2.3.6

**Comment by big-r81** [comment] 2016-07-21 17:19
duplicate of #1065

**Comment by michaelkirk** [comment] 2016-07-21 17:20
closed as dupe of #1065.

**Closed by michaelkirk** 2016-07-21 17:20 UTC
